start-jsk/jsk_apc

- jsk_2014_picking_challenge/launch/visualize_sift.launch
- jsk_2014_picking_challenge/scripts/visualize_sift.py
You can visualize sift keypoints using scripts/visualize_sift.py.
This script is for **test** and **debug**.
Usage
-----
```sh
$ roslauch jsk_2014_picking_challenge visualize_sift.launch test:=true
$ rosservice call /image_publish_server `rospack find jsk_2014_picking_challenge`/data/paste.png
$ rosrun image_view image_view image:=/visualize_sift/output
```
> Add script to visualize sift keypoints

- jsk_2014_picking_challenge/euslisp/motion/pick-object.l
- jsk_2014_picking_challenge/euslisp/robot-init.l
- jsk_2014_picking_challenge/euslisp/robot-main.l
- jsk_2014_picking_challenge/launch/challenge.launch
@wkentaro I changed someparts.
- We need to type `(apc-init)` and `(main)` . If you want to execute without typing every time, please type as below
```
roseus robot-main.l "(progn (apc-init)(main))"
```
and If you want to execute in launch, automatically, please write like as below link
https://github.com/jsk-ros-pkg/jsk_demos/blob/master/jsk_2013_04_pr2_610/launch/demo_common.launch#L17
- I added simulater mode , below parts check the `*ri*` is simulator mode or not. You can access with `*simulator-p*` as global variables.
- With this, in pick-objects, skipping the grap check loop.
```
(setq *simulator-p* (not (send *ri* :joint-action-enable)))
```
> add Simulator Mode

- jsk_2014_picking_challenge/euslisp/motion/check-if-grabbed.l
Relative issue: https://github.com/start-jsk/2014-semi/issues/370
> [euslisp/motion/check-if-grabbed.l] remove ros-info in callback func

- jsk_2014_picking_challenge/euslisp/robot-main.l
- jsk_2014_picking_challenge/euslisp/utils.l
**Usage**
```
> (underscore-to-space "oreo_mega_stuf")
"oreo mega stuf"
```
> [utils.l] Add underscore-to-space for speaking

- jsk_2014_picking_challenge/euslisp/robot-main.l
When targeting center bin, wait opposite arm to finish one order.
(this is realized by waiting if opposite state)
> [robot-main.l] improve waiting for parallel

- jsk_2014_picking_challenge/launch/doura.launch
This will publish BoundingBox. Thanks to @m1a1k0o , we can now publish the pointcloud of below objects in shelf
```
/extract_g_indices/box_array
/extract_h_indices/box_array
/extract_i_indices/box_array
/extract_j_indices/box_array
/extract_k_indices/box_array
/extract_l_indices/box_array
```
> Publish BoundingBox in doura.launch

- jsk_2015_05_baxter_apc/launch/baxter_world.launch
(既に他の方法が実装済かも知れませんが)
以下図のように Baxter の前に棚を出したい時，折角モデルを `jsk_2015_apc_common` package に置いて頂いてるので，`~/.gazebo` に置き直すとかしたくないと思いました．
> Flexible env var for APC shelf model for Gazebo

- jsk_2016_01_baxter_apc/scripts/interface_generator_pick.py
- jsk_2016_01_baxter_apc/scripts/interface_generator_stow.py
@knorth55 Sorry for my git management skill. I had to close old pull request.
> what do you mean bin_A to bin_L for stow tasks?
bin_A to bin_L for stow exist to represent what items does each bin contains already.
The official rule (_http://amazonpickingchallenge.org/APC_2016_Official_Rules.pdf_) says
> The Pick Input File will consist of a single JSON file that defines two things:
> • The initial item contents of all bins on the shelf face
> • The work order detailing what items should be picked from each bin
bin_A to bin_L are to represent the initial item contents of all bins.
> add interface_generator

- jsk_2016_01_baxter_apc/CMakeLists.txt
- jsk_2016_01_baxter_apc/package.xml
- Order
- missing build_depend on roseus
- missing 'CONPONENTS'
Modified:
- jsk_2016_01_baxter_apc/CMakeLists.txt
- jsk_2016_01_baxter_apc/package.xml
> [jsk_2016_01_baxter_apc] Fix catkin config of 'jsk_2016_01_baxter_apc'

- jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
add softkinetic overlook pose method, the position where the camera can see totally inside of a bin.
cc. @yuyu2172
> [jsk_2016_01_baxter_apc] Softkinetic overlook pose

- jsk_2016_01_baxter_apc/firmware/gripper_front_manager_right.ino
baxter.launchがkillされた時にサーボのトルクをオフにするようにしました。
どのbranchでも必要な変更だと思ったのでmasterとgripper-v2の両方にPRを送りました。
firmware自体はすでにarduinoに書き込まれているため、両方のbranchでmergeする必要がないと判断された場合には閉じてもらっても構わないです。
> [jsk_2016_01_baxter_apc] fixed arduino firmware to disable torque when serial_node.py is killed.

- .gitmodules
- jsk_apc2016_common/CMakeLists.txt
A piece of commit divided from #1332.
Added a submodule that contains a code and dataset distributed on [gitlab](https://gitlab.tubit.tu-berlin.de/rbo-lab/rbo-apc-object-segmentation).
The submodule is imported from a mirrored repository on my github account [https://github.com/yuyu2172/rbo-apc-object-segmentation](https://github.com/yuyu2172/rbo-apc-object-segmentation).
I have decided to mirror the files on my personal page because it was the fastest way to make things work using git submodules.
A downturn of mirroring the file is that the files are managed under my personal page even though all members of APC2016 should have equal privileges.
> [jsk_apc2016_common] add rbo's code as a submodule

- jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
fixes #1382 
`(send *ri* :ik->bin-entrance :rarm :c)`とすると、
のようにIKが解けるが、今まではグリッパー関節の角度は90度で固定されていた。今回のPRでは、`(send *ri* :ik->bin-entrance :rarm :c :gripper-angle 0)`のように、グリッパー関節の角度を指定することができるようになり、以下のようにIKが解ける。
これにより、`:ik->bin-entrance`を使っている部分でグリッパーを伸ばすことができるようになり、Binの入口より手前でグリッパーを伸ばすことができるようになった。その他、グリッパーを入口近くで伸ばさないよう、オフセットを若干変更している。
> [jsk_2016_01_baxter_apc] not to knock down objects

- jsk_apc2016_common/python/jsk_apc2016_common/segmentation_in_bin/rbo_segmentation_in_bin.py
Previously, the image returned by RBO's segmentation algorithm zoomed into mask of a bin.
I fixed it to unzoom from the bin.
What the returned segment look like with rgb image on background.
> [jsk_apc2016_common] unzoom returned prediction

- jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
グリッパー関節が曲がっていない時は、グリッパーのローカル座標系のz軸方向にグリッパーを動かすと、物品を持ち上げるのではなく引き出す方向にグリッパーを動かすことになる。今までは、物品を持ち上げる部分のコードがグリッパー関節が曲がっているときと共通だったので、物品を引き出していた。
これを修正し、引き出す方向ではなく、持ち上げる方向に動かすためのPR。
この変更により、binの入口近くにある物品にグリッパー関節を伸ばしてアプローチした場合に、グリッパーを引きすぎてIKを解いたときにそれまでと連続性が低い姿勢がでることがあるという問題( #1394 の実験中にBin eで発生)も同時に解決する。
> [jsk_2016_01_baxter_apc] adjust lifting of objects when gripper is straight

- jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
今までは、`(send *ri* :ik->bin-entrance :rarm :h :offset #f(-200 0 -30))`とすると、以下のような姿勢が得られていた。
しかし、この姿勢では、右アームとBaxter本体が下のように干渉している。
これにより、右グリッパーをBin hから引き出す途中でアームの動きが止まり、その後急に動き出していた。
このPRでは、`:ik->bin-entrance`メソッドにおいて、Binがhの時のみ、グリッパー関節が曲がっていても`:rotation-axis`を`t`にすることにより、`(send *ri* :ik->bin-entrance :rarm :h :offset #f(-200 0 -30))`で以下のような姿勢が得られるようにする。
これにより、アームの急な動きが解消されるはずであるが、まだ実機で試していない。
> [jsk_2016_01_baxter_apc] avoid collision between body and rarm when pulling out rarm from Bin h

- jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
- jsk_2016_01_baxter_apc/test/test-move-arm-to-bin.l
Closes #1405
this is for test-move-arm-to-bin
> [jsk_2016_01_baxter_apc] add revert-if-fail arg for ik->bin-entrance

- jsk_apc2016_common/python/jsk_apc2016_common/segmentation_in_bin/rbo_preprocessing.py
I changed the code to set height data for pixels without depth information to -1.
It follows RBO's convention.
> [jsk_apc2016_common] changed height value for pixel without depth information

- jsk_2016_01_baxter_apc/node_scripts/rbo_segmentation_in_bin_node.py
- jsk_apc2016_common/python/jsk_apc2016_common/segmentation_in_bin/rbo_segmentation_in_bin.py
two fixes
1. Dealt with the case when rosparam 'target_bin' is indeterminate. 
2. initialization of fromBinInfo no longer depends on target_bin
> [jsk_2016_01_baxter_apc] fixed codes that use rosparam target bin 

- jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
Fixes #1383 
このissueでの課題を解決することに加えて、Bin入口で手首が回転した際に、グリッパーの背をBinの横壁に当てることで、棚のモデルと実際の位置がずれていても、物品から十分に離れた位置からアプローチできるようになった。
> [jsk_2016_01_baxter_apc] Adjust approaching object when gripper is 90 degrees

- jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
Fixes #1430 
物品にアプローチしてから吸引を始めることにより、吸引パッドが内側に引き込まれて潰れてしまうことを防止する。
> [jsk_2016_01_baxter_apc] Not to collapse vacuum pad

- jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
When placing an object in order bin, the gripper servo is always powered on. But if the object is very heavy, gripper servo is overloaded when gripper direction and gravity direction aren't the same while bringing the object.
This PR will fix this using `:gripper-servo-off` in `:move-arm-body->order-bin` and `:gripper-servo-on` in `:spin-off-by-wrist`
> [jsk_2016_01_baxter_apc] Don't overload gripper servo when placing object

- jsk_apc2016_common/node_scripts/publish_target_bin_info.py
- jsk_apc2016_common/node_scripts/rbo_segmentation_in_bin_node.py
I made a node that does RBO SIB with very little layer on top of it. Unlike the existing rbo_segmentation_in_bin_node.py, it does not do preprocessing by itself.
For the time being, I put this in a directory "jsk_apc2016_common/node_scripts", and left the existing one. I will delete old codes once transition completes.
> [jsk_apc2016_common][Depends on #1443] make RBO segmentation without preprocessing

- jsk_2016_01_baxter_apc/config/self_filter.yaml
- jsk_2016_01_baxter_apc/launch/include/self_filter.launch
- jsk_2016_01_baxter_apc/launch/recognition_in_hand.launch
- jsk_2016_01_baxter_apc/robots/right_vacuum_gripper.xacro
Fixes #1456 
Add robot self filter for apc2016 robot model like #1458 
Also, change collision meshes of `right_gripper_base` and `right_gripper_vacuum_pad_base` from STL data to URDF boxes and cylinders.
Visual links
Visual and collision links
I'll test this in real robot.
> [jsk_2016_01_baxter_apc] Fix robot self filter for new right gripper

- jsk_2016_01_baxter_apc/euslisp/main.l
> [jsk_2016_01_baxter_apc] Fix return_object for right arm not to collide with bin top

- jsk_apc2016_common/node_scripts/rbo_segmentation_in_bin_node.py
removed patch introduced in #1409.
The patch was necessary because the program ran really slow.
> [jsk_apc2016_common] removed patch on rbo_sib that fixes time stamp to now

- jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter.l
Fixes #1481 
- Use IK to bring end-coords of arms to good positions to see grasped objects.
- Use hash table to manage above good positions
(ex) `(send *ri* (send *baxter* :view-hand-pose :rarm :c))`
> [jsk_2016_01_baxter_apc] Fix view-hand-pose to be robust against gripper change

- jsk_2016_01_baxter_apc/euslisp/main.l
Fixes #1489 
- Add two more midpoints to pass
- Use mapcar to improve extendability
> [jsk_2016_01_baxter_apc] Fix return_object for right arm

- jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
add y-axis angle to look inside the bin.
> [jsk_2016_01_baxter_apc] add y-axis angle of bin-overlook-pose

- jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
From #1470 
again approachでIKが落ちにくくする。
> [jsk_2016_01_baxter_apc] Use rotation-axis z in again approach

- jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
From #1470 
Fixes #1479 
If IK fails when robot tries to approach objects straight down or lift objects, give up to do these motions.
> [jsk_2016_01_baxter_apc] Don't send angle-vector if IK fails in approaching and lifting

- jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
The last commit of this PR fixes #1517 
When jsk-ros-pkg/jsk_pr2eus#227 is fixed, that commit is no more needed.
The other commits are the same as #1515
> [Depends on #1515] [jsk_2016_01_baxter_apc] Avoid bug in robot-interface

- jsk_2016_01_baxter_apc/CMakeLists.txt
with this PR, all xacro's change is deteceted, and baxter.urdf is updated when `catkin build` is executed.
> [jsk_2016_01_baxter_apc] add proper depends on baxter.urdf in CMakeLists

- jsk_2016_01_baxter_apc/CMakeLists.txt
see https://s3.amazonaws.com/archive.travis-ci.org/jobs/132534159/log.txt
```
^M^M                                                                                ^M[jsk_2016_01_baxter_apc:make] [  5%] \
Generating /workspace/ros/ws_jsk_apc/src/jsk_apc/jsk_2016_01_baxter_apc/robots/baxter.dae^M^M^M
^M^M                                                                                ^M[jsk_2016_01_baxter_apc:make] [ERROR]\
[1464090195.203171367]: Error document empty.^M^M^M
^M                                                                                ^M[jsk_2016_01_baxter_apc:make] [ERROR] [\
1464090195.203375662]: failed to open urdf file baxter.urdf^M^M^M
^M^M                                                                                ^M[jsk_2016_01_baxter_apc:make] Segment\
ation …
```
> revert a part of #1525, that genrate baxter.dae twice

- jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
this requires https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/229
tested with 
```
(load "package://jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l")
(load "package://jsk_2015_05_baxter_apc/euslisp/jsk_2015_05_baxter_apc/util.l")
(unless (boundp '*baxter*)
(setq *baxter* (instance jsk_2016_01_baxter_apc::baxter-robot :init)))
(defun setup (&optional (ctype :default-controller))
(jsk_2016_01_baxter_apc::baxter-init :ctype ctype)
(send *ri* :gripper-servo-on)
(send *ri* :angle-vector (send *baxter* :fold-pose-back))
(send *ri* :wait-interpolation)
(objects (list *baxter*))
(setq av1 #f(0.0 97.4707 -2.39502 -94.5483 134.67 91.4062 8.70117 0.0 -5.40301 55.9257 117.063 72.4793 -62.7243 -7.73117 -87.322 90.0))
(setq av2 #f(0.0 97.4707 -2.39502 -94.5483 134.67 91.4062 …
```
> baxter-interface.l : set joint-states-queue-size 2 for gripper and body

- jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
critical error occurs. main.l process has died.
> [jsk_2016_01_baxter_apc] detect :inverse-kinematics nil return

- jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
Closes #1470 
Thanks to #1529 , #1470 will not occur even though using `:rotation-axis t` in again approach.
Also, thanks to #1512 , the robot only give up approaching again and continue to move if IK fails while approaching again.
So, `:rotation-axis :z` is no longer needed.
> [jsk_2016_01_baxter_apc] Revert a part of #1511 thanks to #1529

- jsk_apc2016_common/node_scripts/rbo_segmentation_in_bin_node.py
merge after #1597 
Method segmentation() raises error when it is called with apc2016 bin info. This is because RBO SIB has not been trained with apc2016 dataset.
Current situation is problemetic because some useful debugging data does not get published due to the error.
This PR solves this problem by catching exception and publishing useful data even when error occurs.
> Catch exception for RBOSegmentationInBin.segmentation()

- jsk_2016_01_baxter_apc/src/gripper_trajectory_server.cpp
This PR will make following changes:
- Gripper joint trajectory action server will fill time_from_start in feedback published by it
- Gripper joint trajectory action server will publish feedback continuously even if now isn't in command points
- Gripper joint trajectory action server will sleep until trajectory start time when it receive trajectory
Thanks to them, #1624 will be fixed.
> Fix gripper joint trajectory action server

- jsk_2016_01_baxter_apc/euslisp/examples/picking-with-clustering.l
- jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
Temporarily we need this to run `picking-with-clustering.l`.
I want to use `picking-with-clustering.l` to test grippers easily.
> Enable to use clustering instead of SIB

- jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
- jsk_2016_01_baxter_apc/euslisp/main-stow.l
Closes #1676 
When robot grasp large object
- put the object in proper bin
- enter in bin with offset :z +50
- exit from bin with offset :z 0
When exiting from bin
- rotate gripper to 0
> Use higher trajectory and rotate gripper for entering large object in bin

- fc.rosinstall
Reported but not yet released: https://github.com/ros-drivers/axis_camera/issues/46
> Install axis_camera from source because of its bug

- fc.rosinstall
- jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
I'll check if this is effective for rawlings_baseball, easter_turtle_sippy_cup, kleenex_tissue_box, soft_white_lightbulb, folgers_classic_roast_coffee and up_glucose_bottle. They easily slide too far when gripper push them.
> Use wait-interpolation-smooth for objects not to run away from gripper

- jsk_2016_01_baxter_apc/package.xml
deb build is broken and removed from release repositories
see http://build.ros.org/view/Ibin_uT64/job/Ibin_uT64__jsk_2016_01_baxter_apc__ubuntu_trusty_amd64__binary/
```
Removed Packages [2]:
- ros-indigo-jsk-2016-01-baxter-apc
- ros-indigo-jsk-apc
```
http://lists.ros.org/pipermail/ros-users/2016-June/070033.html
> fix broken build

- jsk_2016_01_baxter_apc/euslisp/examples/picking-with-sib.l
With this PR, picking-with-sib.l works without kinect head.
> Remove :recognize-objects-in-bin in picking-with-sib.l

- jsk_2016_01_baxter_apc/euslisp/main.l
Wait time is too short especially when an arm has moved from a previous position.
> wait longer before starting to subscribe to sib result

- jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
#1808 で勘違いをしていました。
要素がnilのみのlistを設定していたのは、https://github.com/start-jsk/jsk_apc/blob/master/jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l#L458 やhttps://github.com/start-jsk/jsk_apc/blob/master/jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l#L463 で`elt`を使用しており、listでないとエラーが出てくるだろうと思ったからでしたが、`:try-to-pick-object`に入る前のhttps://github.com/start-jsk/jsk_apc/blob/master/jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l#L728-L732 で、すでにnilかどうかのチェックができており、listを設定する必要はなかったです。
> Set nil instead of list when no object found

- jsk_2016_01_baxter_apc/launch/include/astra_hand.launch
Without this PR, cameras did not publish depth registered points.
FYI, sheeta is equipped with titan X. It can run all launch files by itself.
> depth register works with explicit arg

- jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
- jsk_2016_01_baxter_apc/launch/baxter.launch
- jsk_2016_01_baxter_apc/launch/in_bin_data_collection.launch
- jsk_2016_01_baxter_apc/launch/main.launch
- jsk_2016_01_baxter_apc/launch/main_stow.launch
- jsk_2016_01_baxter_apc/test/test_move_arm_to_bin.test
This is useful because we can use baxter-interface.l without main.launch or main_stow.lauch.
> Publish bin bounding boxes in baxter.launch

- jsk_2016_01_baxter_apc/launch/include/baxter_sim.xml
- jsk_2016_01_baxter_apc/robots/baxter.xacro
APC simulation is modified to follow baxter_simulator v1.2
Require this PR https://github.com/RethinkRobotics/baxter_simulator/pull/88
> fix apc2016 simulation for baxter_simulator v1.2

- jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
error
```
2.irteusgl$ send *ri* :fold-pose-back
Unknown limb is passed: :arms
(#f(0.0 20.0 -25.0 -40.0 60.0 -20.0 80.0 0.0 0.0 -20.0 -25.0 40.0 60.0 20.0 80.0 0.0 0.0))
```
> fix error Unknown limb is passed: :arms

- jsk_2016_01_baxter_apc/check_baxter_pkg_version.sh
You can just run in shell:
```
rospack list | awk '{print $1}' | grep baxter | xargs -t -n1 rosversion
```
> Remove check_baxter_pkg_version.sh that is not used

- jsk_2016_01_baxter_apc/launch/include/baxter_sim.xml
without this node, Baxter in simulator does not move with roseus because of error below.
```
[ERROR] [1478767017.396381972, 20.989000000]: Could not start controller with name left_gripper_controller because no controller with this name exists
[ERROR] [1478767017.396454711, 20.989000000]: Could not start controller with name right_gripper_controller because no controller with this name exists
[ERROR] [1478767017.396497205, 20.989000000]: Failed to switch controllers
[ERROR] [1478767017.396525654, 20.989000000]: Failed to switch controllers
```
this gripper_trajectory_server is a dummy and do nothing for gazebo because gripper joint is not loaded in gazebo.
> add gripper_trajectory_server for simulator

- jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
Requires https://github.com/jsk-ros-pkg/jsk_robot/pull/719
> set nil not to initialize default moveit config in baxter-interface

- fc.rosinstall
This is for wstool.
I'll remove this commit when gripper-v5 is merged to master.
> Change jsk_apc branch to gripper-v5

- fc.rosinstall
Depends on #1943 
`gripper-v5-devel` branch in pazeshun/dynamixel_motor includes arebgun/dynamixel_motor#67 and arebgun/dynamixel_motor#68. Without those PRs, we can't use Multi-turn mode of Dynamixel motor from dynamixel_motor package.
> Add dynamixel-motor package to fc.rosinstall

- jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
merge after #1941 or #1939 
default: moveit is disabled.
in case you want to use moveit, you need to set key `:moveit` `t`
```
(jsk_2016_01_baxter_apc::baxter-init :moveit t)
```
> add moveit-environment in baxter-interface

- README.md
- jsk_2016_01_baxter_apc/firmware/udev/80-dxhub.rules
- jsk_2016_01_baxter_apc/launch/include/gripper_dxl_controller.launch
- jsk_2016_01_baxter_apc/scripts/create_udev_rules
This PR allows the connection between gripper-v5 and PC not to depend on device file number(`/dev/ttyUSB0`...)
> Add udev rules for gripper-v5

- jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter.l
* Adjust link name to gripper-v5: `right_gripper_vacuum_pad_base`->`right_gripper_pad_with_base`
* gripper-v5 has two joints, so I removed those two joints from link list
> Don't use right gripper joints to solve IK

- fc.rosinstall
this repo is for jsk_apc.
Make collision head smaller than before.
It makes moveit to solve path successfully.
> update baxter_common repo in fc.rosinstall

- jsk_2016_01_baxter_apc/launch/include/trajectory_execution.launch.xml
trajectory_execution namespace is wrong.
see https://github.com/ros-planning/moveit/issues/61
> fix trajectory_execution namespace

- jsk_2016_01_baxter_apc/euslisp/examples/picking-with-sib.l
- jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
To follow 2c768428141ee7c9e4ad16f732688f91dc7c145a and 178240324e56606eb98b1dd3e8196d77c3d7abf4
> Adjust picking-with-sib to current object segmentation

- jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
* When all IK fails, `:ik->nearest-pose` returns nil, but forgets to revert `*baxter*`'s angle-vector to the one before `(send *baxter* :angle-vector pose)`
* The opposite arm moves after `:ik->nearest-pose`
> Fix :ik->nearest-pose not to move arms unintendedly

- jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter.l
* Add `:ik-prepared-poses` method to jsk_2016_01_baxter_apc::baxter-robot in order to use the feature in https://github.com/jsk-ros-pkg/jsk_robot/commit/a530df140a9f7dafdc4946da4a0f59e03452831b
* Add `:set-ik-prepared-poses` method to change the return value of `:ik-prepared-poses` in order to set initial pose of IK used when normal IK fails
```
14.irteusgl$ send *baxter* :angle-vector av1
#f(0.0 84.7218 11.3176 -100.769 137.239 60.5701 25.7966 34.7697 0.0 -17.7207 -42.6019 132.521 78.9492 -102.309 60.9403 -137.432 0.0)
15.irteusgl$ send *baxter* :ik-prepared-poses
(:untuck-pose)
16.irteusgl$ send *baxter* :rarm :inverse-kinematics ec
; failed for normal ik, starting from relaxed position
; failed for normal ik, try to move arms very slowly
; failed for slow ik, try to start from prepared …
```
> Enable to set ik-prepared-poses

- jsk_arc2017_baxter/CMakeLists.txt
- jsk_arc2017_baxter/package.xml
Without this change, we have error of failed finding of jsk_2016_01_baxter_apc at `find_package` in test block.
> Depends at test time on jsk_2016_01_baxter_apc

- jsk_2016_01_baxter_apc/config/right_gripper_v5/dxl_controllers.yaml
I found this change is needed for safety in Robomech 2017 demo.
> Fix torque limit of prismatic joint in gripper-v5

- jsk_arc2017_common/package.xml
Fix #2088 
- because install_data.py is run in Cmake
> Fix missing build depend on jsk_data

- jsk_2016_01_baxter_apc/package.xml
it may build error reported in #2070 
for `jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/util.l`
> add roseus_mongo as run_depend

- jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
This causes `(send *ri* :wait-interpolation)` does not finish when you use `:default-controller`.
> fix default-controller not to set head-controller twice

- jsk_arc2017_baxter/euslisp/pick-main.l
:wait-interpolationがなかった時は、binの側面に手をぶつけていました。
> fix :pick_object

- jsk_apc2016_common/launch/object_segmentation_3d.launch
The name of chainer model should be passed to `model_h5` param.
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_perception/node_scripts/fcn_object_segmentation.py#L58
> Pass chainermodel name to correct param

- jsk_apc2016_common/CMakeLists.txt
- jsk_apc2016_common/package.xml
someone need to compile jsk_gui_msgs
```
jsk_apc$ grep jsk_gui_msgs -r *
jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxterrgv5-interface.l:                                "/rviz/yes_no_button" (instance jsk_gui_msgs::YesNoRequest)) :yes))
jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l:                                "/rviz/yes_no_button" (instance jsk_gui_msgs::YesNoRequest)) :yes))
jsk_arc2017_baxter/euslisp/lib/arc-interface.l:                                "/rviz/yes_no_button" (instance jsk_gui_msgs::YesNoRequest)) :yes)))
```
> add jsk_gui_msgs to jsk_apc_common

- jsk_2016_01_baxter_apc/data/astra/stereo_left_astra_mini_8_rgb.yaml
- jsk_2016_01_baxter_apc/data/astra/stereo_right_astra_mini_10_rgb.yaml
`stereo_left_astra_mini_8_rgb.yaml` means TEPRA code such as "ASTRA MINI S 2017/04/11 8/10"
`stereo_right_astra_mini_10_rgb.yaml` means TEPRA code such as "ASTRA MINI S 2017/04/11 10/10"
> add calibration yaml files of astra mini stereo

- jsk_arc2017_baxter/CMakeLists.txt
- jsk_arc2017_baxter/euslisp/lib/arc-interface.l
- jsk_arc2017_baxter/euslisp/lib/pick-interface.l
- jsk_arc2017_baxter/euslisp/pick-main.l
- jsk_arc2017_baxter/launch/main/pick.launch
- jsk_arc2017_baxter/node_scripts/state_server.py
- jsk_arc2017_baxter/package.xml
- jsk_arc2017_baxter/srv/CheckCanStart.srv
- jsk_arc2017_baxter/srv/GetState.srv
- jsk_arc2017_baxter/srv/UpdateState.srv
Close #2104 and #2110 
Requires https://github.com/jsk-ros-pkg/jsk_roseus/pull/520
- current `pick-main.l` moves to `lib/pick-interface.l`
- `pick-interface` inherits `arc-interface`
- add `state_server.py` for dual-arm picking
- add `UpdateState, GetState, CheckCanStart` srv
- `euslisp` processes set their current state with srv `UpdateState`
- `euslisp` processes check `can-start` with srv `CheckCanStart`
- `GetState` is command line, i.e. `$ rosservice call /state_server/right_hand/get_state` returns `state`.
- Use smach state machine in `pick-main.l`
> Use smach state machine in pick-main.l

- jsk_2016_01_baxter_apc/node_scripts/control_vacuum_gripper.py
```
rosrun jsk_2016_01_baxter_apc control_vacuum_gripper.py --right --stop
rosrun jsk_2016_01_baxter_apc control_vacuum_gripper.py --start
rosrun jsk_2016_01_baxter_apc control_vacuum_gripper.py --right --stop --left
```
> Order agonistic options to control vacuum gripper

- jsk_arc2017_baxter/euslisp/lib/pick-interface.l
- jsk_arc2017_baxter/euslisp/lib/stow-interface.l
Update of #2148 
- add `moveit-p` slot in `pick-inteface` and  `stow-inteface`
> allow :moveit nil  in pick and stow task

- jsk_arc2017_baxter/euslisp/lib/arc-interface.l
Sorry, this is caused by my wrong suggestions below:
https://github.com/start-jsk/jsk_apc/pull/2138#discussion_r121268797
https://github.com/start-jsk/jsk_apc/pull/2138#discussion_r121268805
Translation should be performed before rotation not to apply wrong offset
> Fix translation in ik->bin-center and ik->tote-center

- jsk_arc2017_baxter/launch/setup/baxter.launch
fix typo
`incude`
->
`include`
> fix typo in baxter.launch

- fc.rosinstall
newest `jsk_roseus` is released in https://github.com/ros/rosdistro/pull/15322
> remove released jsk_roseus from fc.rosinstall

- jsk_arc2017_baxter/euslisp/lib/arc-interface.l
- jsk_arc2017_baxter/euslisp/lib/pick-interface.l
- jsk_arc2017_baxter/euslisp/lib/stow-interface.l
- jsk_arc2017_baxter/launch/setup/include/planning_context.launch
- jsk_arc2017_baxter/robots/moveit_config/joint_limits.yaml
- update `joint_limits.yaml` (these values are same as URDF)
- use `angle-vector-sequecne-raw` and `angle-vector-raw`
- current programs are designed to use raw methods with `:fast`
-  but `pr2eus_moveit` supports `:fast` with https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/282,
> Modify joint_limits and use raw angle-vector methods in some part

- doc/conf.py
- doc/jsk_arc2017_baxter/arc2017_stow_trial.rst
- doc/jsk_arc2017_baxter/index.rst
- doc/jsk_arc2017_common/nodes/json_saver.md
- doc/jsk_arc2017_common/nodes/work_order_publisher.md
Close #2193 and #2194 
- add json_saver and work_order_publisher doc
- add jsk_arc2017_baxter stow task doc 
- update copyright year to 2017
> [doc] update docs for stow task and new nodes

- jsk_arc2017_baxter/euslisp/lib/arc-interface.l
- jsk_arc2017_baxter/euslisp/lib/stow-interface.l
when `:get-largest-object-index` fails, this PR prevent error and return `nil` from the method
> return nil when largest bbox subscription timeout

- doc/jsk_arc2017_common/nodes/candidates_publisher.md
- jsk_apc2016_common/launch/object_segmentation_3d.launch
- jsk_arc2017_baxter/euslisp/lib/arc-interface.l
- jsk_arc2017_baxter/euslisp/lib/pick-interface.l
- jsk_arc2017_baxter/euslisp/lib/stow-interface.l
- jsk_arc2017_baxter/launch/main/pick.launch
- jsk_arc2017_baxter/launch/main/stow.launch
- jsk_arc2017_common/CMakeLists.txt
- jsk_arc2017_common/cfg/CandidatesPublisher.cfg
- jsk_arc2017_common/node_scripts/candidates_publisher.py
- jsk_arc2017_common/samples/sample_candidates_publisher.launch
- jsk_arc2017_common/test/candidates_publisher.test
waiting for upstream
require https://github.com/jsk-ros-pkg/jsk_recognition/pull/2143 
related to https://github.com/start-jsk/jsk_apc/issues/2187
- update candidates for segmentation via topic
- add `candidates_publisher.py` node
- add `:set-target-location` method in `arc-interface.l`
> Update candidates for segmentation via topic in order to change candidates dynamically

- fc.rosinstall
Building pcl is optional, because I install it to /usr/local in sheeta.
You can try below in your own pc.
```bash
cd PointCloudLibrary/pcl
mkdir -p build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX:PATH=$HOME/catkin_ws/devel -DBUILD_GPU=1
make -j
make install
```
> Add PointCloudLibrary/pcl to fc.rosinstall

- jsk_arc2017_baxter/euslisp/lib/arc-interface.l
:rarmのままだと左手を使うときに動かないような気がします。
> fix typo  :rarm -> arm

- jsk_arc2017_baxter/euslisp/lib/arc-interface.l
- jsk_arc2017_baxter/euslisp/lib/baxter-interface.l
- jsk_arc2017_baxter/euslisp/lib/baxter.l
Because
- We cannot use left hand with this change.
- Has typo.
北川はやる気をなくしました。
> Revert #2235 'Grasp using proximity'

- jsk_arc2017_baxter/launch/setup/include/stereo_astra_hand.launch
- Calibrate color to depth extrinsic parmaters of cameras.
- Stop using right-side camera to avoid IR conflicts.
- Use software registration for depth registration.
Close #2243
> Calibrate color-depth extrinsic parameters of hand cameras

- jsk_arc2017_common/CMakeLists.txt
- jsk_arc2017_common/cfg/PublishDatasetV3.cfg
- jsk_arc2017_common/launch/publish_dataset_v3.launch
- jsk_arc2017_common/node_scripts/publish_dataset_v3.py
- jsk_arc2017_common/rvizconfig/publish_dataset_v3.rviz
- jsk_arc2017_common/scripts/create_scenes_dataset_v3.py
```
roslaunch jsk_arc2017_baxter baxter.launch moveit:=false
roslaunch jsk_arc2017_baxter stereo_astra_hand.launch
roslaunch jsk_arc2017_baxter collect_data_in_shelf.launch
....
rsync -avt ~/.ros/jsk_arc2017_baxter/dataset_jsk_v3 /data/projects/arc2017/datasets/JSKV3
rosrun jsk_arc2017_common create_scenes_dataset_v3.py
roslaunch jsk_arc2017_baxter publish_dataset_v3.launch
```
Part of https://github.com/start-jsk/jsk_apc/pull/2217
> Publish scenes and view frame of DatasetV3 in ROS

- jsk_arc2017_baxter/euslisp/lib/pick-interface.l
- jsk_arc2017_baxter/euslisp/lib/stow-interface.l
To prevent collision between gripper and shelf or tote
> Move gripper upward in :return-object to prevent collision

- jsk_arc2017_baxter/config/left_gripper_v6/dxl_controllers.yaml
Tendon becomes longer than initial state.
Perhaps the length of tendon will become further longer, but become stable soon like right gripper.
> Re-calibrate left vacuum pad joint

- jsk_arc2017_baxter/euslisp/lib/arc-interface.l
- jsk_arc2017_baxter/euslisp/lib/baxter-interface.l
- jsk_arc2017_baxter/euslisp/lib/pick-interface.l
- jsk_arc2017_baxter/euslisp/lib/stow-interface.l
For #2210 
My idea is we can detect some object is picked by weight scales in `verify-object`.
So we can skip grasping checks of `:try-to-pinch-object` by making `:graspingp` return t when `:pinch` is set.
> Always set graspingp of pinching as true

- jsk_arc2017_baxter/euslisp/lib/baxter-interface.l
This prevents `:hand-interpolatingp` from returning `nil` while hand motion is executed.
(following https://github.com/jsk-ros-pkg/jsk_pr2eus/blob/master/pr2eus/robot-interface.l#L595)
> Update hand action state in :hand-interpolatingp

- jsk_arc2017_baxter/euslisp/lib/arc-interface.l
- jsk_arc2017_baxter/euslisp/lib/pick-interface.l
- jsk_arc2017_baxter/euslisp/lib/stow-interface.l
- jsk_arc2017_baxter/euslisp/pick-main.l
- jsk_arc2017_baxter/euslisp/stow-main.l
after suction picking failure, do not recognize `FCN` again and try pinch.
this is [0] of #2260
> try picking twice and not recognize

- jsk_arc2017_baxter/euslisp/lib/baxter.l
I forgot to fix this in #2232 
Without this fix, we found that prismatic joint in left gripper moves by IK even if we set `:use-gripper nil`
> Fix larm IK to accept :use-gripper nil

- jsk_apc2016_common/launch/object_segmentation_3d.launch
- resize input of `cpi_decomposer_label`
- set smaller `queue_size` for `cpi_decomposer`s
> Make largest object selection faster

- .travis.rosinstall
> Remove released repos from .travis.rosinstall

- jsk_arc2017_baxter/experiments/create_dataset2d/README.md
- jsk_arc2017_baxter/experiments/create_dataset2d/create-dataset2d-collect-rawdata-main.l
- jsk_arc2017_baxter/experiments/create_dataset2d/create_dataset2d_collect_rawdata_main.launch
- jsk_arc2017_baxter/experiments/create_dataset2d/create_dataset2d_data_collection_server.launch
Update version of #2289.
Enabled data collection in Tote, as well as in Shelf bin.
- In Shelf bins
```bash
roslaunch jsk_arc2017_baxter baxter.launch moveit:=false
roslaunch jsk_arc2017_baxter stereo_astra_hand.launch
roslaunch jsk_arc2017_baxter create_dataset2d_rawdata_main.launch
rosrun jsk_arc2017_common view_dataset2d.py ~/.ros/jsk_arc2017_baxter/create_dataset2d/right_hand
```
- In Tote
```bash
roslaunch jsk_arc2017_baxter baxter.launch moveit:=false pick:=false
roslaunch jsk_arc2017_baxter stereo_astra_hand.launch
roslaunch jsk_arc2017_baxter create_dataset2d_rawdata_main.launch box:=tote
rosrun jsk_arc2017_common view_dataset2d.py ~/.ros/jsk_arc2017_baxter/create_dataset2d/right_hand
```
> Enable data collection in tote

- jsk_arc2017_baxter/launch/setup/setup_for_pick.launch
increase weight error.
I tried pick task, and hose weight is around 10-20g.
so I increase error to 20g.
this is temporary solution, so I added FIXME comment.
> increase weight error for pick task

- jsk_arc2017_baxter/euslisp/lib/baxter-interface.l
Depends on https://github.com/pazeshun/dynamixel_motor/pull/4 (Copy of https://github.com/arebgun/dynamixel_motor/pull/78)
For #2328
- (In https://github.com/pazeshun/dynamixel_motor/pull/3) Adjust plus and minus of load and velocity to position of dynamixel motor
- Adjust load direction in `baxter-interface` to the direction fixed in https://github.com/pazeshun/dynamixel_motor/pull/3
> Fix load direction of dynamixel motors

- jsk_arc2017_baxter/euslisp/lib/arc-interface.l
- jsk_arc2017_baxter/euslisp/lib/stow-interface.l
merge after #2313
when `picking-fail-count` > 0, select one from top 3 large objects randomly.
> add n-random key in :get-largest-target-object

- jsk_arc2017_common/launch/object_segmentation_3d.launch
- jsk_arc2017_common/samples/sample_fcn_object_segmentation.launch
Because we changed the strategy to handle the unknown (newly passed)
objects.
> Use class segmentation in known objects

- jsk_arc2017_baxter/euslisp/lib/arc-interface.l
今まではcentroidのz座標にboundingboxのz方向の高さの半分を加えたものをobj-posのz座標にしていましたが、
centroidのz座標をそのままobj-posのz座標にしました。
> use only centroid for determining obj-pos

- jsk_arc2017_baxter/euslisp/lib/baxter-interface.l
In order to avoid collision to other objects in `return-object` or cardboard boxes in `place-object`
> Don't extend prismatic joint in :stop-grasp

- jsk_arc2017_baxter/euslisp/lib/arc-interface.l
- jsk_arc2017_baxter/euslisp/lib/baxter-interface.l
- 劣駆動指が地面か物体にあたる状況を作るため、直動関節を伸ばさない状態で腕を下げる
- `:start-grasp arm :pinch`では直動関節を動かさず、lift objectの後で直動関節を短くして物体を強く把持する
> Improve pinching

- jsk_arc2017_baxter/euslisp/lib/arc-interface.l
pinchしたあとに物体を持ち上げると、グリッパのz軸周りの角度がおかしいままなことがあるので、物体を持ち上げたあとにリセットするようにしました。
> reset gripper rotation after lifting object

- jsk_arc2017_baxter/euslisp/lib/pick-interface.l
I haven't tested with real robot.
> fix typo in place in pick-object

- jsk_arc2017_common/node_scripts/ekew_i_driver.py
- jsk_arc2017_common/node_scripts/weight_candidates_refiner.py
Close https://github.com/start-jsk/jsk_apc/issues/2529
-1 cannot represent unstable state of the scale, because the scale can output minus values.
> Publish nan value when unstable by EkEwIDriver

- jsk_2015_05_baxter_apc/package.xml
```
CMake Error at
/opt/ros/indigo/share/baxter_sim_hardware/cmake/baxter_sim_hardwareConfig.cmake:141
(message):
Project 'jsk_2015_05_baxter_apc' tried to find library
'baxter_sim_hardware'.  The library is neither a target nor
built/installed
properly.  Did you compile project 'baxter_sim_hardware'? Did you
find_package() it before the subdirectory containing its code is
included?
Call Stack (most recent call first):
CMakeLists.txt:21 (find_package)
CMakeLists.txt:97 (select_catkin_dependencies)
```
> Remove run_depend on baxter_sim_hardware to fix error on build.ros.org

- jsk_arc2017_baxter/robots/left_gripper_v6/dxl_controllers.yaml
More torque is needed to rotate yaw joint in new left finger
> Re-calibrate left finger yaw joint

- jsk_arc2017_baxter/euslisp/lib/baxter-interface.l
- jsk_arc2017_baxter/euslisp/lib/baxter.l
15s -> 13s
```
roseus baxter-interface.l "(progn (jsk_arc2017_baxter::baxter-init) (exit))"
```
> Make eus model loading faster

- jsk_arc2017_baxter/src/jsk_arc2017_baxter/calib_required_joint_controller.py
> Fix calibration of prismatic joint

- jsk_arc2017_baxter/euslisp/check-gripper-state.l
Because calibration of prismatic joint may take more than 1 second.
The gripper state never comes until first calibration is finished.
> Make timeout longer in checking gripper state at initial

- jsk_arc2017_baxter/euslisp/lib/pick-interface.l
- jsk_arc2017_baxter/euslisp/lib/stow-interface.l
- jsk_arc2017_baxter/launch/setup/setup_for_stow.launch
Depends on #2574 
- Apply https://github.com/start-jsk/jsk_apc/pull/2556/commits/2079f39c7492bea5943510edb20a871d667884fc in #2556 to stow task
- Fix release motion of pinch in `dropped`
- This is never happened now. I just care about extendability.
> Tune spin-off motions in stow

- fc.rosinstall
Now all programs used at ARC2017 are merged to jsk-ros-pkg/jsk_common.
> Use master branch of jsk_common

- docker/Dockerfile
- docker/build.sh
It takes time to install dependencies on Jenkins using rosdep, without `--from-paths /opt/ros/indigo/share`.
> Update docker config for start-jsk/jsk_apc

- jsk_2016_01_baxter_apc/CMakeLists.txt
- jsk_arc2017_baxter/CMakeLists.txt
I got `No such file or directory "ros/ros.h"`.
> Fix missing include files

- fc.rosinstall
ROBOTIC MATERIALS社のparallel gripper kitに
https://github.com/knorth55/FA-I-sensor/blob/add-proximity-grippers/force_proximity_ros/src/proximity_grippers/proximity_grippers.ino
を書き込んで使おうとしたのですが、コンパイル時に
https://github.com/ros-drivers/rosserial/issues/259
のようなエラーが出ました。
上のissueの通り、rosserialのバージョンを0.7.6にしたらコンパイルが通るようになり、値が読めるようになりました。
> version up rosserial in fc.rosintall

- jsk_arc2017_baxter/euslisp/lib/baxter-interface.l
Baxter moves while succeeding in grasping, and stops to move when grasp failure is detected.
I use this in my experiment: https://github.com/mmurooka/euslib/blob/murooka-branch/demo/murooka/wholebody_manipulation_planner/demo_robot_carry_object/euslisp/demo-baxter-carry-block.l#L161.
If this is useful for APC, please use. otherwise, please close.
> [jsk_arc2017_baxter] ungrasp condition in :wait-interpolation-until

- doc/jsk_arc2017_baxter/state_machine.rst
> fix typo in doc

- .travis.yml
This enables us remove cron jobs from Jenkins.
> Trigger the build of the docker image after_success

- jsk_arc2017_baxter/euslisp/lib/baxter-interface.l
`:speak` method is added to the robot-interface which is the super class of baxter-interface.
> Fix *ri* :speak method according to the upstream change

- fc.rosinstall
Because of https://github.com/ros-perception/image_pipeline/pull/299, `image_proc/resize` is corrupted.
We need to use `1.12.20`.
> use image_proc 1.12.20

- jsk_arc2017_baxter/robots/left_gripper_v7.xacro
- jsk_arc2017_baxter/robots/left_vacuum_gripper.xacro
- jsk_arc2017_baxter/robots/right_vacuum_gripper.xacro
I found that right gripper (gripper-v6) is collapsed in baxterlgv7 merged in #2612 
The cause is name collision in `xacro:property`.
`right_vacuum_gripper.xacro` and  `left_gripper_v7.xacro` have the same properties and the latter overwrites the former.
This problem is also occurred between `right_vacuum_gripper.xacro` and `left_vacuum_gripper.xacro` in default baxter in jsk_arc2017_baxter, but I couldn't find because the change is very small.
Add `rg_` and `lg_` to property names:
```
diff --git a/jsk_arc2017_baxter/robots/left_gripper_v7.xacro b/jsk_arc2017_baxter/robots/left_gripper_v7.xacro
index 1ee41e1..6c1e0ec 100644
--- a/jsk_arc2017_baxter/robots/left_gripper_v7.xacro
+++ b/jsk_arc2017_baxter/robots/left_gripper_v7.xacro
@@ -45,55 +45,55 @@ …
```
> Avoid name clashes in gripper xacro

- jsk_arc2017_baxter/euslisp/lib/baxterlgv7.l
- jsk_arc2017_baxter/robots/left_gripper_v7.xacro
This fixes palm coordinate of left gripper_v7 (mistake in #2612 ).
- Palm coordinate in URDF
- Before
- After
- Palm coordinate in Euslisp (it's transformed from one in URDF for pinching) 
- Before
- After
> Fix palm endpoint of left gripper_v7

- jsk_arc2017_baxter/euslisp/lib/pick-interface.l
While placing object to left side cardboard with rarm in pick task, IK fails.
It occurs when grasp-style is 'pinch', so probably Baxter cannot reach cardboard.
If object is not dropped, ignore IK failure and force to release object.
Tested with real robot.
(Thanks @pazeshun )
> Ignore IK failure when placing

- jsk_arc2017_common/config/object_weights.yaml
Even after resetting scales, all of  4 scales indicate that the weight of poland_spring_water is 494g or 495g.
> Modify weight of poland_spring_water

- jsk_arc2017_common/data/models/.gitignore
- jsk_arc2017_common/node_scripts/candidates_publisher.py
- jsk_arc2017_common/python/jsk_arc2017_common/utils.py
- Don't ignore fcn32s.npz to remove it by git clean
for git clean
- Skip empty bin while visualizing JSON
To make visualization better.
- Fix unreasonable ~json_dir param to candidates_publisher
a bug introduced by https://github.com/start-jsk/jsk_apc/pull/2618
> Fixes for demo on 2018-01-19

- jsk_arc2017_baxter/euslisp/lib/baxter.l
I clean up codes.
Same IK was solved twice, which was bottleneck
> clean up ik->nearest-pose

- jsk_2016_01_baxter_apc/robots/baxter_simple.urdf
collision head was modified to original big one in https://github.com/start-jsk/jsk_apc/pull/2311
it was as small as this PR in ARC2017 (https://github.com/knorth55/baxter_common/commit/a722703d2ab67df252e0a98aac32f91bffc845f5)
> use smaller collision head

- jsk_arc2017_baxter/launch/setup/include/axis_camera.launch
Because IP address sometimes changes.
> Specify axis camera with hostname instead of ip address

- jsk_arc2017_baxter/launch/setup/include/record_rosbag.launch
When `/<left/right>_hand_camera/right/depth/image_raw/compressedDepth` is recorded, IR projection of right side is started, which makes IR conflicts fixed in #2244
> Don't record right side depth to avoid IR conflicts

- .travis.rosinstall.kinetic
- .travis.yml
- jsk_2016_01_baxter_apc/euslisp/lib/baxter-interface.l
- jsk_2016_01_baxter_apc/euslisp/lib/util.l
- jsk_2016_01_baxter_apc/package.xml
- jsk_arc2017_baxter/include/jsk_arc2017_baxter/tendon_transmission_loader.h
- jsk_arc2017_baxter/src/tendon_transmission_loader.cpp
Build failure on `jsk_arc2017_baxter` in Kinetic.
Because of this change in Kinetic. https://github.com/ros-controls/ros_control/pull/324
This change is quite huge :(.
Change is 
- `TransmissionPtr` -> `transmission_interface::TransmissionSharedPtr`
```cpp
Starting  >>> jsk_arc2017_baxter                                                                    
____________________________________________________________________________________________________
Errors     << jsk_arc2017_baxter:make /home/shingo/ros/kinetic/logs/jsk_arc2017_baxter/build.make.026.log
In file included from /home/shingo/ros/kinetic/src/start-jsk/jsk_apc/jsk_arc2017_baxter/src/tendon_transmission_loader.cpp:16:0:
/home/shingo/ros/kinetic/src/start-jsk/jsk_apc/jsk_arc2017_baxter/include/jsk_arc2017_baxter/tendon_transm …
```
> Fix Kinetic build

- jsk_arc2017_baxter/robots/right_gripper_v6/dxl_controllers.yaml
Because the finger tendon pulley in right hand is chipped:
> Re-calibrate finger tendon winder

- fc.rosinstall
- jsk_arc2017_baxter/include/jsk_arc2017_baxter/tendon_transmission_loader.h
jsk_visualization 2.1.3 is released which includes the commit we need:
https://github.com/jsk-ros-pkg/jsk_visualization/commit/ceaa9333d14fd627c80671ccef76cf0302fc1d75 
http://repositories.ros.org/status_page/ros_indigo_default.html?q=jsk_visualization
> Remove jsk_visualization from fc.rosinstall

- fc.rosinstall
- jsk_arc2017_baxter/include/jsk_arc2017_baxter/tendon_transmission_loader.h
Now image_proc 1.12.23 is released.
http://repositories.ros.org/status_page/ros_indigo_default.html?q=image_proc
> Remove image_proc 1.12.20 from fc.rosinstall

- .travis.yml
If the test fails, new docker image can be helpful,
so it should be triggered at both after_success and failure.
For https://github.com/start-jsk/jsk_apc/pull/2645#issuecomment-408699375
> Trigger docker build at after_script

- jsk_arc2017_baxter/euslisp/lib/stow-interface.l
For experiments without the scales.
> Add :use-scale option to :pick-object of stow-interface

- jsk_arc2017_baxter/euslisp/lib/stow-interface.l
In current ARC workspace moving head is not so necessary.
> Add :move-head option to :pick-object of stow-interface

- jsk_arc2017_baxter/euslisp/lib/arc-interface.l
I need this to request the name of the subscribed bounding box
by using a service call to a image pipeline node which has a map from timestamp to object name.
> Return recognized timestamp in :recognize-target-object

- jsk_arc2017_baxter/euslisp/lib/stow-interface.l
I need this to move the picked object quickly to a free space inside the bin since the motion of avoiding tote is very slow.
> Option not avoiding tote after :pick-object

- jsk_arc2017_baxter/euslisp/lib/arc-interface.l
I found scale 5.0 is too fast.
(Maybe this needs the fact by a video.)
> Make it slower to send avs for smoother motion (going to above target object)

- .travis.yml
- README.md
I created https://hub.docker.com/r/jskrobotics/jsk_apc/ and use this instead of wkentaro/jsk_apc in order to keep maintained by jsk lab.
> Use docker image under jsk organization

- demos/grasp_fusion/ros/grasp_fusion/CMakeLists.txt
- demos/instance_occlsegm/requirements.txt
- demos/instance_occlsegm/ros/instance_occlsegm/CMakeLists.txt
Depends on #2698 
Updated version of #2697 
When building jsk_apc with .travis.rosinstall and .travis.rosinstall.kinetic, I encountered the following error at `instance_occlsegm`:
```
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-W46fSl/pycocotools/
```
This is because `Cython` is not automatically installed before installing `pycocotools`:
```
$ pip install --user pycocotools
Collecting pycocotools
Downloading https://files.pythonhosted.org/packages/96/84/9a07b1095fd8555ba3f3d519517c8743c2554a245f9476e5e39869f948d2/pycocotools-2.0.0.tar.gz (1.5MB)
100% |████████████████████████████████| 1.5MB 308kB/s 
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File …
```
> Fix errors in building grasp_fusion and instance_occlsegm

- .travis.rosinstall
- fc.rosinstall.indigo
- fc.rosinstall.kinetic
- upboard.rosinstall
Because https://github.com/RoboticMaterials/FA-I-sensor/pull/11 is merged
> Change FA-I-sensor to root repository in *.rosinstall

- jsk_arc2017_baxter/launch/setup/include/stereo_astra_hand.launch
When subscribing compressedDepth on kinetic, hz of image_raw drops.
This is because load of CPU processing camera becomes too high.
To avoid this on baxter-c1, png_level should be under 6.
This behavior is different from indigo, so we should do further investigation...
I created https://github.com/ros-perception/image_common/issues/151 to gather information.
cc. @YutoUchimi
> [jsk_arc2017_baxter] Set png_level of compressedDepth to keep image_raw hz on kinetic

- .travis.yml
- doc/jsk_2015_05_baxter_apc/apc2015_demo_sim.rst
- jsk_2015_05_baxter_apc/euslisp/lib/baxter-interface.l
- jsk_2015_05_baxter_apc/launch/baxter_sim.launch
- jsk_2015_05_baxter_apc/launch/setup_head.launch
- jsk_2015_05_baxter_apc/robots/baxter.xacro
- jsk_2015_05_baxter_apc/robots/baxter_sim.xacro
- sim.rosinstall.indigo
- sim.rosinstall.kinetic
- sim.rosinstall.melodic
update amazon picking challenge 2015 simulation doc
> Fix Amazon Picking Challenge 2015 Simulation

- doc/jsk_arc2017_baxter/arc2017_pick_trial.rst
- doc/jsk_arc2017_baxter/arc2017_stow_trial.rst
- doc/jsk_arc2017_baxter/state_machine.rst
- jsk_arc2017_common/scripts/download_pick_re-experiment.py
- jsk_arc2017_common/scripts/install_pick_re-experiment
I did the following:
1. Upload sharable ARC2017 data owned by @wkentaro to [google drive folder](https://drive.google.com/drive/folders/1fN2ZF-gvCromymyCBa1WzTHP6G4ym5tR) (accessible from [jsk_apc doc](https://jsk-apc.readthedocs.io/en/latest/jsk_arc2017_baxter/index.html#shared-data))
2. Add script to install pick_re-experiment (experiment imitating ARC2017 pick competition)
3. Add doc of how to execute pick_re-experiment
Other minor fix:
- Change sheeta to baxter-c1 in ARC2017 doc
> [jsk_arc2017_common] Add script to install pick_re-experiment (experiment imitating ARC2017 pick competition)

- demos/grasp_fusion/requirements.txt
- demos/instance_occlsegm/requirements.txt
opencv-python is no longer support python2.7.
I set to use `4.2.0.32` which is the last support version for python2.7
https://github.com/skvark/opencv-python/issues/152
https://github.com/skvark/opencv-python/releases/tag/34
> set opencv-python version to 4.2.0.32

- demos/grasp_fusion/ros/grasp_fusion/CMakeLists.txt
- demos/grasp_prediction_arc2017/ros/grasp_prediction_arc2017/CMakeLists.txt
- demos/instance_occlsegm/ros/instance_occlsegm/CMakeLists.txt
disable `CHECK_VENV` which causes build failure
https://github.com/locusrobotics/catkin_virtualenv/pull/62
> disable CHECK_VENV in catkin_virtualenv 0.6.1

- README.md
- docker/Dockerfile
- update docker build badge in readme
- install python >=2.7.9 for indigo
- because of non-SNI compatible client
- related issue: https://github.com/pypa/pypi-support/issues/978
- related website: https://status.python.org/incidents/hzmjhqsdjqgb
- jsk_travis solution: https://github.com/jsk-ros-pkg/jsk_travis/commit/1acceab886c3c3e315ae7c057730566c938eafb5
- install `dlib<19.22` for indigo
- dlib drop gcc 4.8 support
- related issue: https://github.com/davisking/dlib/issues/2354
> fix docker build for indigo

- fc.rosinstall.melodic
latest moveit removes move_group/MoveGroupExecuteService
we need these commits.
https://github.com/ros-planning/moveit_robots/commit/707b86b43ba2a0bda1d27ce2019f798d9d79005a
https://github.com/ros-planning/moveit_robots/commit/3514d389b45361b19af936099af45090912ec1f1
> install moveit_robots from source

- .github/workflows/indigo.yaml
- .github/workflows/kinetic.yml
- .github/workflows/melodic.yml
- .github/workflows/python2.yml
- .travis.rosinstall.kinetic
- .travis.rosinstall.melodic
- .travis.yml
- demos/grasp_fusion/requirements.txt
- demos/instance_occlsegm/requirements.txt
this PR is from #2746 
- use latest catkin_virtualenv
- https://github.com/locusrobotics/catkin_virtualenv/pull/85 is merged, we can use the origin/master branch
- fix permission issue reported in https://github.com/jsk-ros-pkg/jsk_travis/pull/445
- fix protobuf version
- add python2 syntax test
> update .travis.rosinstall for kinetic and melodic

- demos/grasp_prediction_arc2017/grasp_prediction_arc2017_lib/contrib/grasp_prediction_arc2017/datasets/item_data_dataset.py
This broken link was caused by reducing GoogleDrive storage size.
> Fix broken link to Hasegawa data
