start-jsk/jsk_apc

.travis.yml

remove (indigo USE_DEB=true) travis test from allow_failures

---

jsk_2014_picking_challenge/CMakeLists.txt
jsk_2014_picking_challenge/euslisp/object-picking-action-server-class.l
jsk_2014_picking_challenge/launch/demo_real.launch
jsk_2014_picking_challenge/msg/bin_content.msg
jsk_2014_picking_challenge/msg/bins_content.msg
jsk_2014_picking_challenge/scripts/object_picking_client.py
jsk_2014_picking_challenge/scripts/object_picking_test.py
jsk_2014_picking_challenge/scripts/read_json.py

Add object picking actionlib-server by euslisp (class ver.).

Add object picking actionlib-server.

---

jsk_2014_picking_challenge/package.xml
jsk_2014_picking_challenge/scripts/read_json.py

https://github.com/start-jsk/2014-semi/issues/129

resolve not assigned queue_size warning

---

jsk_2014_picking_challenge/euslisp/main.l
jsk_2014_picking_challenge/euslisp/move-arm2target-bin-server.l

* Compute IK without axis allowance.
* Enable main.l test inserting arm to the bins.

Enhance move2target for actual object picking from bins

---

jsk_2014_picking_challenge/euslisp/apc_tweet.l
jsk_2014_picking_challenge/launch/final_video.launch
jsk_2014_picking_challenge/launch/passthrough_image.launch

Not confirmed yes. Don't merge.

add apc_tweet.l

---

jsk_2014_picking_challenge/CMakeLists.txt
jsk_2014_picking_challenge/cfg/ColorCutback.cfg
jsk_2014_picking_challenge/launch/color_histogram_matcher.launch
jsk_2014_picking_challenge/scripts/color_cutbacker.py

#184 
* color_cutbacker.py
jsk_perception/rgb_decomposer, hsv_decomposerでrgb/hsvに分割した画像を受け取り、指定された(reference)色情報に対して閾値を設け、画像を変換した後高さ1の画像を出力する。

Remove chroma from color histogram matcher

---

jsk_2014_picking_challenge/data/example.json

http://amazonpickingchallenge.org/example.json
を少し変更したものです。（棚に4品入っていたりするのをなくした）

Add example json with all items in the shelf

---

jsk_2014_picking_challenge/data/.gitignore
jsk_2014_picking_challenge/data/object_list.yml
jsk_2014_picking_challenge/launch/extract_color_histogram.launch
jsk_2014_picking_challenge/launch/lab_color_histogram_matcher.launch
jsk_2014_picking_challenge/launch/rgb_color_histogram_matcher.launch
jsk_2014_picking_challenge/launch/test_color_histogram_matching.launch
jsk_2014_picking_challenge/scripts/color_cutback.py
jsk_2014_picking_challenge/scripts/color_histogram_matcher.py
jsk_2014_picking_challenge/scripts/extract_color_histogram.py
jsk_2014_picking_challenge/test/test_color_histogram_matcher.py

Use LAB color space as well as RGB

---

jsk_2014_picking_challenge/data/.gitignore
jsk_2014_picking_challenge/data/object_list.yml

[object_list.yml] Add new objects (newly added to rll.berkeley.edu)

---

jsk_2014_picking_challenge/config/baxter_white_hand.urdf.xacro
jsk_2014_picking_challenge/launch/upload_baxter.launch

Change the length of the colisiion

Update Baxter urdf model for long vacuum hand

---

jsk_2014_picking_challenge/config/baxter_white_hand.urdf
jsk_2014_picking_challenge/config/baxter_white_hand.urdf.xacro
jsk_2014_picking_challenge/launch/upload_baxter.launch

Add new baxter long vacuum DAE

---

jsk_2014_picking_challenge/firmware/switching_gripper.cpp

圧力センサで掃除機が掴んでいるか掴んでないかを、
/grabbed_gripper/stateでpublishするようにしました。

modified: check wheather grabbed

---

jsk_2014_picking_challenge/CMakeLists.txt
jsk_2014_picking_challenge/data/.gitignore
jsk_2014_picking_challenge/data/test_result/test_bof_matching_result.csv
jsk_2014_picking_challenge/launch/bof_object_matcher.launch
jsk_2014_picking_challenge/launch/test_bof_object_matcher.launch
jsk_2014_picking_challenge/msg/ObjectRecognition.msg
jsk_2014_picking_challenge/package.xml
jsk_2014_picking_challenge/scripts/bag_of_features.py
jsk_2014_picking_challenge/scripts/bof_object_matcher.py
jsk_2014_picking_challenge/scripts/extract_bof_histograms.py
jsk_2014_picking_challenge/scripts/matcher_common.py
jsk_2014_picking_challenge/scripts/train_bof_histogram_clf.py
jsk_2014_picking_challenge/test/test_object_matching.py

**Attention** Firstly extract sift features using `extract_sift_from_objdata.py`.
Extract
```
$ roscore
$ rosrun jsk_2014_picking_challenge extract_sift_bof_histograms.py
```
Classify ( test )
```
$ roslaunch jsk_2014_picking_challenge test_bof_object_matcher.launch
```
test result is stored at `data/test_result/test_bof_matching_result.csv`
Classify ( real time)
```
$ roslaunch jsk_2014_picking_challenge bof_object_matcher.launch
```

Add BagOfFeatures histogram extractor and classifier for object verification

---

README.md

Update README to add How to execute DEMO

---

README.md

Sorry, I couldn't merge from @wkentaro  before the branch merged.
So this will be a new PR.

Update readme for execution to use challenge.launch

---

jsk_2014_picking_challenge/euslisp/arm-motion.l
jsk_2014_picking_challenge/test/measure-fastest-time.l

Tweet check

---

jsk_2014_picking_challenge/euslisp/arm-motion.l

https://github.com/start-jsk/2014-semi/issues/219
ランダムなパターンを５つ作ってつかむようにしました。

Random grasp 219

---

jsk_2014_picking_challenge/launch/edge_icp_registration.launch
jsk_2014_picking_challenge/launch/edge_publisher.launch

For #245 
This needs edge pcd data.
This still doesn't include eus model position registration.
Next PR I will send eus model position modification and publish Bin eus model marker in rviz.

add edge icp registration launch

---

jsk_2014_picking_challenge/euslisp/motion/return-object.l
jsk_2014_picking_challenge/euslisp/utils.l

return-object :larm
or
return-object :rarm

modified return-object

---

jsk_2014_picking_challenge/euslisp/robot-init.l

⚠!!!! THIS WILL BE VERY CRITICAL !!!!⚠

move end-coords

---

jsk_2014_picking_challenge/scripts/interface_generator.py

roscd jsk_2014_picking_challenge/data
rosrun jsk_2014_picking_challenge interface_generator.py
cat apc.json

[interface_generator.py] Initial commit

---

jsk_2014_picking_challenge/euslisp/robot-init.l

maybe fit end-coords with real robot

---

jsk_2014_picking_challenge/config/openni_self_filter_custom.yaml

Related #272
Finnaly, the cylinder seems to be enough to remove the pointcloud.
I couldn't find out the reasons.
Kinect2's tf seesm to be a little bit wrong, so please fix it .

update Baxter self filter params

---

README.md

baxterのver1.1.0を使うことになっているためパッチはいりません。

remove unneeded line

---

README.md

#353 
You need to compile from source.

add sound_play install part to README

---

jsk_2014_picking_challenge/euslisp/robot-init.l
jsk_2014_picking_challenge/euslisp/robot-main.l
jsk_2014_picking_challenge/euslisp/robot-visualization.l
jsk_2014_picking_challenge/euslisp/utils.l

Move all visualization code to ros-visuzalition.l

add ros-visualization.l

---

jsk_2014_picking_challenge/launch/challenge.launch

add basefootprint for baxter

---

jsk_2014_picking_challenge/config/challenge.rviz

add Challenge rviz config

---

jsk_2014_picking_challenge/launch/attention_divide.launch
jsk_2014_picking_challenge/launch/passthrough_image.launch
jsk_2014_picking_challenge/launch/process_mask_image.launch

Advise from @garaemon
BE CAREFUL THIS WILL CHANGE THE PASSTHROUGH LAUNCH
- divinding to two file.

add left right dividing passthrough

---

jsk_2014_picking_challenge/scripts/reset.sh
jsk_2014_picking_challenge/scripts/show.sh

for #389 
```
$ ./reset.sh a pick_object
/target           is a
/left_limb/state  is pick_object
/right_limb/state is pick_object
```

add simple reset and show related param script

---

jsk_2014_picking_challenge/euslisp/motion/verify-object.l

[verify_object] Add timeout feature

---

jsk_2014_picking_challenge/euslisp/robot-main.l

[robot_main] Abbreviate verification if already tried picking enough

---

jsk_2014_picking_challenge/euslisp/robot-main.l

[robot_main] abort if already tried to pick many times

---

.gitattributes
jsk_2014_picking_challenge/euslisp/motion/check-if-grabbed.l
jsk_2014_picking_challenge/euslisp/motion/control-vacuum-gripper.l
jsk_2014_picking_challenge/euslisp/motion/get-work-order.l
jsk_2014_picking_challenge/euslisp/motion/move-for-verification.l
jsk_2014_picking_challenge/euslisp/motion/move-to-target-bin.l
jsk_2014_picking_challenge/euslisp/motion/pick-object.l
jsk_2014_picking_challenge/euslisp/motion/place-object.l
jsk_2014_picking_challenge/euslisp/motion/return-object.l
jsk_2014_picking_challenge/euslisp/motion/robot-motion-common.l
jsk_2014_picking_challenge/euslisp/motion/tweet.l
jsk_2014_picking_challenge/euslisp/motion/verify-object.l
jsk_2014_picking_challenge/euslisp/robot-init.l
jsk_2014_picking_challenge/euslisp/robot-main.l
jsk_2014_picking_challenge/euslisp/robot-motions.l
jsk_2014_picking_challenge/euslisp/robot-test.l
jsk_2014_picking_challenge/euslisp/robot-visualization.l
jsk_2014_picking_challenge/euslisp/utils.l

See: https://github.com/wkentaro/2014-semi/blob/github-syntax-highlight/jsk_2014_picking_challenge/euslisp/robot-init.l

Add modeline of emacs/vim to add highlight on GitHub

---

jsk_2014_picking_challenge/launch/attention_divide.launch

update attention clipper box params

---

jsk_2014_picking_challenge/launch/attention_divide.launch
jsk_2014_picking_challenge/launch/process_mask_image.launch

We never use the attention clipper because of speed

make recognition a little bit faster

---

jsk_2014_picking_challenge/config/baxter_joint_trajectory.yaml
jsk_2014_picking_challenge/launch/upload_baxter.launch

We will change this values finally to -1

upload baxter_joint_trajectroy params

---

jsk_2014_picking_challenge/euslisp/motion/pick-object.l

**PLEASE DON'T MERGE THIS** before I check this efficiency with actual robot

[pick_object] Add see if grabbed in picking

---

jsk_2014_picking_challenge/firmware/switching_gripper_left.cpp
jsk_2014_picking_challenge/firmware/switching_gripper_right.cpp

minor change: add debug button  to arduino program

add debug button

---

jsk_2014_picking_challenge/launch/baxter_world.launch
jsk_2014_picking_challenge/scripts/setup_baxter_gazebo.py

roslaunch jsk_2014_picking_challenge baxter_world.launch

Add gazebo setup node

---

jsk_2014_picking_challenge/euslisp/robot-visualization.l

add if-yet to some advertise

---

jsk_2014_picking_challenge/euslisp/robot-visualization.l

add new colorized pod

---

jsk_2014_picking_challenge/scripts/objects_marker_server.py

fix color material variable in marker

---

jsk_2014_picking_challenge/meshes/champion_copper_plus_spark_plug/champion_copper_plus_spark_plug.dae
jsk_2014_picking_challenge/meshes/cheezit_big_original/cheezit_big_original.dae
jsk_2014_picking_challenge/meshes/crayola_64_ct/crayola_64_ct.dae
jsk_2014_picking_challenge/meshes/dove_beauty_bar/dove_beauty_bar.dae
jsk_2014_picking_challenge/meshes/dr_browns_bottle_brush/dr_browns_bottle_brush.dae
jsk_2014_picking_challenge/meshes/elmers_washable_no_run_school_glue/elmers_washable_no_run_school_glue.dae
jsk_2014_picking_challenge/meshes/expo_dry_erase_board_eraser/expo_dry_erase_board_eraser.dae
jsk_2014_picking_challenge/meshes/feline_greenies_dental_treats/feline_greenies_dental_treats.dae
jsk_2014_picking_challenge/meshes/first_years_take_and_toss_straw_cups/first_years_take_and_toss_straw_cups.dae
jsk_2014_picking_challenge/meshes/genuine_joe_plastic_stir_sticks/genuine_joe_plastic_stir_sticks.dae
jsk_2014_picking_challenge/meshes/highland_6539_self_stick_notes/highland_6539_self_stick_notes.dae
jsk_2014_picking_challenge/meshes/kong_air_dog_squeakair_tennis_ball/kong_air_dog_squeakair_tennis_ball.dae
jsk_2014_picking_challenge/meshes/kong_duck_dog_toy/kong_duck_dog_toy.dae
jsk_2014_picking_challenge/meshes/kong_sitting_frog_dog_toy/kong_sitting_frog_dog_toy.dae
jsk_2014_picking_challenge/meshes/kyjen_squeakin_eggs_plush_puppies/kyjen_squeakin_eggs_plush_puppies.dae
jsk_2014_picking_challenge/meshes/laugh_out_loud_joke_book/laugh_out_loud_joke_book.dae
jsk_2014_picking_challenge/meshes/mark_twain_huckleberry_finn/mark_twain_huckleberry_finn.dae
jsk_2014_picking_challenge/meshes/mead_index_cards/mead_index_cards.dae
jsk_2014_picking_challenge/meshes/mommys_helper_outlet_plugs/mommys_helper_outlet_plugs.dae
jsk_2014_picking_challenge/meshes/munchkin_white_hot_duck_bath_toy/munchkin_white_hot_duck_bath_toy.dae
jsk_2014_picking_challenge/meshes/one_with_nature_soap_dead_sea_mud/one_with_nature_soap_dead_sea_mud.dae
jsk_2014_picking_challenge/meshes/oreo_mega_stuf/oreo_mega_stuf.dae
jsk_2014_picking_challenge/meshes/paper_mate_12_count_mirado_black_warrior/paper_mate_12_count_mirado_black_warrior.dae
jsk_2014_picking_challenge/meshes/safety_works_safety_glasses/safety_works_safety_glasses.dae
jsk_2014_picking_challenge/meshes/sharpie_accent_tank_style_highlighters/sharpie_accent_tank_style_highlighters.dae
jsk_2014_picking_challenge/meshes/stanley_66_052/stanley_66_052.dae

set ambient and emission higher to show more light

---

jsk_2014_picking_challenge/euslisp/robot-main.l
jsk_2014_picking_challenge/launch/challenge.launch

This should be moved to pick-object after improving the recognition of checking if grabbed.

[robot-main.l] temporary check if grabbed in robot-main.l

---

jsk_2014_picking_challenge/launch/attention_divide.launch

fix reversed right and left region

---

jsk_2014_picking_challenge/launch/baxter.launch

add customizing baxter.launch for challenge

---

jsk_2014_picking_challenge/euslisp/robot-communication.l
jsk_2014_picking_challenge/euslisp/robot-main.l
jsk_2014_picking_challenge/launch/challenge.launch
jsk_2014_picking_challenge/launch/image_saver.launch

Add tweet-with-image

---

jsk_2014_picking_challenge/scripts/score_calculator.py

[score_calculator.py] add including objects print line

---

jsk_2014_picking_challenge/config/challenge.rviz
jsk_2014_picking_challenge/euslisp/robot-main.l
jsk_2014_picking_challenge/euslisp/robot-visualization.l

add status overlay texts

---

jsk_2014_picking_challenge/firmware/switching_gripper_left.cpp
jsk_2014_picking_challenge/firmware/switching_gripper_right.cpp
jsk_2014_picking_challenge/launch/rosserial.launch

for serial read error, I change it.

change delay 1 -> 1000 and change baud_rate to 115200

---

jsk_2014_picking_challenge/scripts/check_state.py

For  #540
This is still not perfect.
DON'T MERGE UNTIL I DO

add check state script for before start

---

jsk_2014_picking_challenge/scripts/interface_generator2.py

from https://github.com/Jorge-C/apc_random_orders

[interface_generator2.py] add generator

---

jsk_2014_picking_challenge/euslisp/motion/return-object.l
jsk_2014_picking_challenge/euslisp/robot-init.l

PLEASE **WAIT** FOR ME TO TEST WITH ACTUAL ROBOT

[return_object] Insert arm to deep pos in the bin

---

jsk_2014_picking_challenge/data/.gitignore
jsk_2014_picking_challenge/data/appropriate_images.yml

fix robot-communication to use them, tweet and tweet-with-images functions just to send toipc to tweet_server and retuns

change object name

---

jsk_2014_picking_challenge/CMakeLists.txt
jsk_2014_picking_challenge/package.xml
jsk_2014_picking_challenge/scripts/work_order.py
jsk_2014_picking_challenge/test/interface_test.py
jsk_2014_picking_challenge/test/test_robot_input.py

**実行の仕方**
```
catkin bt --start-with-this --no-deps --catkin-make-args test
```

Add unittest for robot_input

---

jsk_2014_picking_challenge/launch/baxter.launch

DON'T MERGE UNTIL https://github.com/jsk-ros-pkg/jsk_robot/pull/334 merge

add launch_mongodb param to baxter.launch

---

jsk_2014_picking_challenge/firmware/switching_gripper_left.cpp
jsk_2014_picking_challenge/firmware/switching_gripper_right.cpp

spinOnceを常にするようにして、bufferがつまらないようにしました。

delete delay after spinOnce

---

jsk_2014_picking_challenge/config/challenge.rviz
jsk_2014_picking_challenge/scripts/debug_info_overlay_text.py

add debug_info_overlay_text.py

---

jsk_2014_picking_challenge/data/apc-f.json
jsk_2014_picking_challenge/data/apc-g.json

add  apc-f and apc-g

---

jsk_2014_picking_challenge/euslisp/robot-input.l
jsk_2014_picking_challenge/euslisp/robot-recognition.l
jsk_2014_picking_challenge/launch/image_saver.launch

We think
- Set lambda function as subscriber callback isno't recommended.
- Especially call defenition twice(e.g. load file twice)

don't use lambda

---

jsk_2014_picking_challenge/euslisp/robot-visualization.l

Update point pictogram popup position

---

jsk_2014_picking_challenge/scripts/debug_info_overlay_text.py

Suppress queue_size warning in debug_info

---

jsk_2014_picking_challenge/scripts/objects_marker_server.py

make interactive marker bigger

---

jsk_2014_picking_challenge/euslisp/motion/pick-object.l
jsk_2014_picking_challenge/euslisp/motion/robot-motion-common.l

I changed try-to-pick-object like (defun try-to-pick-object (arm bin pattern depth)) to add pattern with pick-object.

Add pick pattern

---

jsk_2014_picking_challenge/euslisp/robot-input.l
jsk_2014_picking_challenge/scripts/setup_params.py

add total score param

---

jsk_2014_picking_challenge/scripts/vacuum_force.py

for https://github.com/start-jsk/2014-semi/issues/302

publish /gripper_grabbed/limb/left/state2, checking wrench forces

---

jsk_2014_picking_challenge/config/baxter_joint_trajectory.yaml

そろそろ間際なので、パラちゅんをすることもしなくてはなりませんが、
とりあえず-1.0に設定してabortしないようにします。

all set the joint_trajectory vaule to -1.0

---

jsk_2014_picking_challenge/launch/attention_divide.launch
jsk_2014_picking_challenge/launch/setup.launch

認識周りに対する変更です。
3時のテストでおかしかったらこのPRを疑ってください。

make faster the recognition

---

jsk_2014_picking_challenge/config/challenge.rviz
jsk_2014_picking_challenge/scripts/debug_info_overlay_text.py

add grabbed and timer msg

---

jsk_2014_picking_challenge/scripts/check_shelf_pos.l

check shelf pos scripts (eus)

---

jsk_2014_picking_challenge/scripts/show_setup_readme.py

念の為、
手順をscriptで確認できるようにしましたが、実際に使うかはわかりません。

add show-setup-readme.py for make sure the command

---

jsk_2014_picking_challenge/scripts/record_axis_video.py

```
rosrun jsk_2014_picking_challenge record_axis_video.py
```

Add axis video recorder

---

jsk_2014_picking_challenge/launch/edge_icp_registration.launch
jsk_2014_picking_challenge/launch/edge_publisher.launch

This will fit the edge of doura 's input with ICP
The output will be published to /icp_registration/output_pose ?
blue - pcd file input
white - kinect2 input
red - result

setup icp registration for doura

---

jsk_2014_picking_challenge/euslisp/debug.l
jsk_2014_picking_challenge/euslisp/motion/pick-object.l
jsk_2014_picking_challenge/euslisp/motion/robot-motion-common.l
jsk_2014_picking_challenge/euslisp/robot-recognition.l
jsk_2014_picking_challenge/euslisp/robot-test.l
jsk_2014_picking_challenge/euslisp/test_object_recognition.py

I adjusted pick-object's parameter.

Adjust pick object

---

jsk_2014_picking_challenge/euslisp/motion/pick-object.l
jsk_2014_picking_challenge/euslisp/robot-recognition.l

@iory 
Please check if this is ok for you.

[motion/pick-object.l] Add lines for see-if-grabbed to pick champion

---

jsk_2014_picking_challenge/euslisp/robot-recognition.l

[robot-recognition.l] Add timeout in see-if-grabbed

---

jsk_2014_picking_challenge/euslisp/motion/pick-object.l

add label pattern to pick-object

---

jsk_2014_picking_challenge/euslisp/motion/pick-object.l

modified label selecting function

---

jsk_2014_picking_challenge/euslisp/robot-test.l

modified check-if-grabed's argument change's error

fix pick-offset error caused by check-if-grabed's arguments change

---

jsk_2014_picking_challenge/euslisp/motion/pick-object.l

add stop-grasp for test

---

jsk_2014_baxter_apc/config/baxter_white_hand.urdf.xacro
jsk_2014_baxter_apc/launch/kinect2_tf.launch

Adjust kinect2 tf and baxter custom link after calibration of kinect2

---

jsk_2015_05_baxter_apc/launch/kinect2_torso.launch

[jsk_2015_05_baxter_apc] roslaunch for kinect2_torso

---

.travis.yml

See: http://blog.travis-ci.com/2015-10-14-opening-up-ubuntu-trusty-beta

Set dist: trusty on travis

---

jsk_2015_05_baxter_apc/launch/kinect2_head.launch

[jsk_2015_05_baxter_apc] Adjust kinect2_head tf

---

jsk_2015_05_baxter_apc/euslisp/jsk_2015_05_baxter_apc/baxter-interface.l
jsk_2015_05_baxter_apc/launch/baxter.launch
jsk_2015_05_baxter_apc/launch/include/filter_reachable_cloud.launch
jsk_2015_05_baxter_apc/launch/include/kinect2_head.launch
jsk_2015_05_baxter_apc/launch/include/kinect2_torso.launch
jsk_2015_05_baxter_apc/launch/include/self_filter.launch
jsk_2015_05_baxter_apc/launch/recognition_in_hand.launch
jsk_2015_05_baxter_apc/launch/setup.launch

[jsk_2015_05_baxter_apc] Make faster localization in hand

---

jsk_2015_05_baxter_apc/launch/doura.launch
jsk_2015_05_baxter_apc/launch/setup.launch

in sheeta
```
roslaunch jsk_2015_05_baxter_apc baxter.launch
roslaunch jsk_2015_05_baxter_apc setup.launch
```
in doura
```
roslaunch jsk_2015_05_baxter_apc doura.launch
```

[jsk_2015_05_baxter_apc] Add doura.launch

---

jsk_2015_05_baxter_apc/test/test_segmentation_in_hand.test
jsk_2015_05_baxter_apc/test_data/.gitignore

Depends on https://github.com/jsk-ros-pkg/jsk_common/pull/1240

[jsk_2015_05_baxter_apc] Test recognitioin in hand

---

.travis.rosinstall
jsk_2015_05_baxter_apc/launch/include/self_filter.launch
jsk_2015_05_baxter_apc/launch/recognition_in_hand.launch

This is no need with change in
PR2/pr2_navigation/pr2_navigation_self_filter
Related to https://github.com/PR2/pr2_navigation/pull/24

[jsk_2015_05_baxter_apc] Remove approximate_sync (no need)

---

jsk_2015_05_baxter_apc/launch/include/kiva_pod_state.launch

Modified:
- jsk_2015_05_baxter_apc/launch/include/kiva_pod_state.launch

[jsk_2015_05_baxter_apc] Remove kiva_pod joint_state_publisher

---

jsk_2015_05_baxter_apc/launch/include/kinect2_torso.launch

Update tf of kinect2 torso

---

jsk_2015_05_baxter_apc/euslisp/jsk_2015_05_baxter_apc/baxter-interface.l

Modified:
- jsk_2015_05_baxter_apc/euslisp/jsk_2015_05_baxter_apc/baxter-interface.l

[jsk_2015_05_baxter_apc] Add place-object method

---

jsk_2015_05_baxter_apc/euslisp/examples/picking-with-clustering.l

Add sample of picking with clustering points

---

README.md

Closes https://github.com/start-jsk/jsk_apc/issues/1041

Describe how to setup laptop

---

jsk_2015_05_baxter_apc/CMakeLists.txt
jsk_2015_05_baxter_apc/README.md
jsk_2015_05_baxter_apc/include/gazebo_plugins/gazebo_ros_vacuum_gripper.h
jsk_2015_05_baxter_apc/rosinstall
jsk_2015_05_baxter_apc/src/gazebo_ros_vacuum_gripper.cpp

upstream: https://github.com/ros-simulation/gazebo_ros_pkgs/pull/389

[jsk_2015_05_baxter_apc] Add gazebo vacuum gripper plugin

---

jsk_2016_01_baxter_apc/launch/include/baxter_sim.xml

[2016apc] change baxter software version

---

README.md
kinect2.rosinstall

Add kinect2.rosinstall versioned used actually

---

jsk_2015_05_baxter_apc/euslisp/jsk_2015_05_baxter_apc/baxter-interface.l
jsk_2015_05_baxter_apc/euslisp/jsk_2015_05_baxter_apc/baxter.l
jsk_2015_05_baxter_apc/euslisp/main.l
jsk_2015_05_baxter_apc/launch/doura.launch
jsk_2015_05_baxter_apc/launch/setup.launch

https://drive.google.com/folderview?id=0B9P1L--7Wd2vLU4zODBLdWc3bmM&usp=sharing

[jsk_2015_05_baxter_apc] Faster pick-and-verify approach

---

jsk_2016_01_baxter_apc/json/apc_pick.json
jsk_2016_01_baxter_apc/json/apc_stow.json

This is required for making baxter simulation for 2016 apc.
@knorth55 is this right?

[jsk_2016_01_baxter_apc] Sample json files for APC2016

---

jsk_2016_01_baxter_apc/README.md

Modified:
- jsk_2016_01_baxter_apc/README.md

Add Shared files for jsk_2016_01_baxter_apc

---

.travis.rosinstall
jsk_2015_05_baxter_apc/CMakeLists.txt
jsk_2015_05_baxter_apc/test/test_recognition_in_hand.test

Fix roslaunch args for recognition test

---

jsk_2016_01_baxter_apc/json/pick_layout_1.json

Json file for picking: Layout1

---

jsk_apc2015_common/src/jsk_apc2015_common/__init__.py

Modified:
- jsk_apc2015_common/src/jsk_apc2015_common/__init__.py

Dynamic visualization for given number of bin_contents

---

jsk_2015_05_baxter_apc/euslisp/jsk_2015_05_baxter_apc/util.l

Modified:
- jsk_2015_05_baxter_apc/euslisp/jsk_2015_05_baxter_apc/util.l

Add utility functions for handling hashtable

---

jsk_2016_01_baxter_apc/scripts/interface_generator_pick.py
jsk_2016_01_baxter_apc/scripts/interface_generator_stow.py

Improvement : This considers number of objects in lab for generate json.
closes #1100

interface_generator modified for apc2016

---

jsk_2016_01_baxter_apc/scripts/interface_generator_pick.py
jsk_2016_01_baxter_apc/scripts/interface_generator_stow.py

interface_generator modified not to update pre-generated JSON
#1143 
#1136

interface_generator modified not to update pre-generated JSON

---

README.md

Add badge of readthedocs on README

---

README.md

Fix link of usage of this repo

---

README.md

Add description about this repo in README

---

README.md

Use bold (not itelic) for jsk_apc

---

doc/conf.py
doc/jsk_apc2015_common/index.rst
doc/jsk_apc2015_common/python.rst
jsk_apc2015_common/src/jsk_apc2015_common/__init__.py

[jsk_apc2015_common] Doc for python library

---

jsk_apc2015_common/src/jsk_apc2015_common/__init__.py

This removes the error in readthedocs when importing the lib.

Use python lib not in ros environement

---

doc/conf.py
doc/jsk_apc2016_common/index.rst
doc/jsk_apc2016_common/python.rst
jsk_apc2016_common/CMakeLists.txt
jsk_apc2016_common/package.xml
jsk_apc2016_common/python/jsk_apc2016_common/__init__.py

This tests the style of the code.

Add roslint_test for python library

---

doc/_static/css/modified_theme.css
doc/conf.py

Colorize documentation as red

---

jsk_2015_05_baxter_apc/rosinstall

Refine rosinstall

---

jsk_2015_05_baxter_apc/launch/segmentation_in_bin_atof.launch
jsk_2015_05_baxter_apc/launch/segmentation_in_bin_gtol.launch
jsk_2015_05_baxter_apc/launch/setup_head.launch
jsk_2015_05_baxter_apc/launch/setup_torso.launch

[jsk_2015_05_baxter_apc] Visualize segmentation in bin

---

jsk_2016_01_baxter_apc/launch/include/viz_recognition.launch
jsk_2016_01_baxter_apc/node_scripts/rect_label_to_image.py

Visualize object recognition result and probability and object's region in image

[jsk_2016_01_baxter_apc] visualize object recognition results

---

jsk_2016_01_baxter_apc/node_scripts/work_order.py

[jsk_2016_01_baxter_apc] add blacklist for bin contents

---

doc/tips_faq.rst

cythonのversionについてのtipsを書きました。問題点があれば指摘していただければ幸いです。

added tips of cython

---

jsk_2015_05_baxter_apc/package.xml

[jsk_2015_05_baxter_apc] Generate eus robot model from xacro

---

jsk_2016_01_baxter_apc/launch/baxter.launch
jsk_2016_01_baxter_apc/launch/include/vacuum_gripper.launch

jsk_2016_01_baxter_apcにbaxter.launchを追加し、新グリッパーにつけるarduinoのrosserial nodeをbaxter.launchから起動できるように変更。  @ban-masa がfirmwareを完成させたら、それに合わせてbaud rateの変更を行う。

[jsk_2016_01_baxter_apc] add baxter.launch and new arduino node

---

jsk_2016_01_baxter_apc/firmware/arm_manager.ino
jsk_2016_01_baxter_apc/firmware/gripper_front_manager_right.ino

This is an arduino firmware for baxter arms.
Please merge this.

Arduino firmware for baxter arms

---

jsk_2016_01_baxter_apc/launch/setup_creative.launch
jsk_2016_01_baxter_apc/robots/baxter.xacro
jsk_2016_01_baxter_apc/robots/right_vaccum_gripper.xacro

[jsk_2016_01_baxter_apc] Added creative camera on baxter's rightarm

---

jsk_2016_01_baxter_apc/launch/setup_creative.launch

Modified:
- jsk_2016_01_baxter_apc/launch/setup_creative.launch

[jsk_2016_01_baxter_apc] Get organized point cloud from softkinetic camera

---

jsk_2016_01_baxter_apc/robots/baxter.xacro
jsk_2016_01_baxter_apc/robots/left_arm_camera.xacro
jsk_2016_01_baxter_apc/robots/right_arm_camera.xacro

[jsk_2016_01_baxter_apc] add softkinetic xacro

---

jsk_2016_01_baxter_apc/launch/setup_softkinetic.launch

[jsk_2016_01_baxter_apc] add right arm depthsense camera

---

jsk_2016_01_baxter_apc/launch/baxter.launch

#1286 
jsk-ros-pkg/jsk_robot#589
It may be a temporary change. When [jsk_robot package](https://github.com/jsk-ros-pkg/jsk_robot) fixes, we will enable tweet.
Please merge this.

[jsk_2016_01_baxter_apc] disable tweet

---

jsk_2016_01_baxter_apc/launch/setup_softkinetic.launch

[jsk_2016_01_baxter_apc] modify setup_creative.launch to launch devices by serial number

---

jsk_2016_01_baxter_apc/launch/setup_softkinetic.launch

[jsk_2016_01_baxter_apc] Image format fixed

---

jsk_2016_01_baxter_apc/launch/setup_softkinetic.launch

Merge after #1282
change device: CREATIVE camera -> DepthSense camera

[jsk_2016_01_baxter_apc] modify softkinetic camera serial number on right hand

---

jsk_2016_01_baxter_apc/data/softkinetic/137DS32528260700377/calib_color.yaml
jsk_2016_01_baxter_apc/data/softkinetic/137DS32528260700380/calib_color.yaml
jsk_2016_01_baxter_apc/launch/setup_softkinetic.launch

pick better softkinetic device and calibrate color image

[jsk_2016_01_baxter_apc] Calibrate softkinetic 2016/04/17

---

jsk_2016_01_baxter_apc/CMakeLists.txt
jsk_2016_01_baxter_apc/launch/baxter.launch
jsk_2016_01_baxter_apc/package.xml
jsk_2016_01_baxter_apc/src/gripper_joint_states_publisher.cpp

Added gripper_joint_states_publisher.cpp whiech subscribes angle of the right servo and publishes joint_states.
merge after #1286

[jsk_2016_01_baxter_apc] added gripper_joint_states_publisher.cpp

---

jsk_2016_01_baxter_apc/CMakeLists.txt
jsk_2016_01_baxter_apc/launch/baxter.launch
jsk_2016_01_baxter_apc/src/gripper_trajectory_server.cpp

Added gripper_trajectory_server.cpp which converts a servo angle msg(Float32) into a joint state msg(JointState).

[jsk_2016_01_baxter_apc]Add gripper_trajectory_action_server

---

jsk_2016_01_baxter_apc/CMakeLists.txt
jsk_2016_01_baxter_apc/node_scripts/work_order.py
jsk_2016_01_baxter_apc/package.xml
jsk_2016_01_baxter_apc/test/work_order.test

[jsk_2016_01_baxter_apc] work order fixed

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/include/baxter-interface.l
jsk_2016_01_baxter_apc/euslisp/main.l
jsk_2016_01_baxter_apc/launch/baxter.launch
jsk_2016_01_baxter_apc/robots/right_vacuum_gripper.xacro

Add Lisp methods to power on/off gripper servo. If #1302 is merged, I will rebase origin/master and erase the WIP tag.

[jsk_2016_01_baxter_apc] Use real new gripper from Euslisp

---

doc/jsk_2016_01_baxter_apc/milestone/stable_achievement_30points_with_new_gripper.rst

New milestone for a new gripper.

Added stable_achievement_30points_with_new_gripper.rst

---

jsk_2016_01_baxter_apc/src/gripper_trajectory_server.cpp

[jsk_2016_01_baxter_apc] fix gripper_trajectory_server's info and extendability

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/include/baxter-interface.l

fixes #1317 
Please merge this.

[jsk_2016_01_baxter_apc] fix default-controller of baxter-interface.l

---

doc/jsk_2016_01_baxter_apc/logs/2016-04-21.rst

[jsk_2016_01_baxter_apc] add 2016-04-21 log

---

doc/jsk_2016_01_baxter_apc/logs/2016-04-22-gripper.rst

[jsk_2016_01_baxter_apc] add 2016-04-22-gripper log

---

jsk_2016_01_baxter_apc/firmware/gripper_front_manager_right.ino

Fixed arduino firmware to subscribe gripper_front/enable.
Fixed arduino firmware to subscribe gripper_front/limb/right/servo/angle while torque is off.

[jsk_2016_01_baxter_apc] Fixed Arduino firmware

---

jsk_2016_01_baxter_apc/CMakeLists.txt
jsk_2016_01_baxter_apc/launch/baxter.launch
jsk_2016_01_baxter_apc/package.xml
jsk_2016_01_baxter_apc/src/enable_gripper.cpp

From #1297 , #1327 .
This node works with new Arduino firmware @ban-masa will make.

[jsk_2016_01_baxter_apc] Add enable_gripper node enabling grippers and managing automatic power off

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l

this is for ik-unsolvable region
#1209

[jsk_2016_baxter_apc] remember angle-vector to pull out arm from bin

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l

Change offsets of right arm to avoid collisions.

[jsk_2016_01_baxter_apc] avoid collision between new gripper and bin

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l

[jsk_2016_01_baxter_apc] use gripper servo off not to release objects

---

jsk_2016_01_baxter_apc/launch/recognition_in_hand.launch
jsk_2016_01_baxter_apc/launch/setup_torso.launch

in_hand_clipper frame and bounding box is modified for 2016 gripper
Close #1339

[jsk_2016_baxter_apc] add recognition_in_hand and setup_torso

---

doc/jsk_2016_01_baxter_apc/logs/2016-04-25-26-gripper.rst

[jsk_2016_01_baxter_apc] add log 2016-04-25-26-gripper

---

jsk_2016_01_baxter_apc/euslisp/examples/picking-with-clustering.l

Ported of picking-with-clustering.l in jsk_2015_05_baxter_apc.

[jsk_2016_01_baxter_apc] add picking only code

---

jsk_apc2016_common/scripts/train_segmenter.py

saves trained segmentation object as a pkl on (jsk_apc2016_common)/data/

[jsk_apc2016_common] add training script for the rbo_segmentation

---

.gitmodules

Now follow jsk_apc branch
https://github.com/yuyu2172/rbo-apc-object-segmentation
The branch is also updated. Now data class APCData accepts matrix as input.

[jsk_apc2016_common] update rbo_segmentation submodule

---

jsk_apc2016_common/python/jsk_apc2016_common/mask_bin.py

Generate region of an image that corresponds to the target bin.

[jsk_apc2016_common] add a script that generates mask image of the target bin

---

.travis.rosinstall
.travis.yml

Cherry pick #1375 to gripper-v2 branch

[jsk_2016_01_baxter_apc] Cherry pick #1375

---

jsk_2016_01_baxter_apc/CMakeLists.txt
jsk_2016_01_baxter_apc/package.xml
jsk_2016_01_baxter_apc/scripts/download_test_data.sh
jsk_2016_01_baxter_apc/test/test-move-arm-to-bin.l
jsk_2016_01_baxter_apc/test/test_move_arm_to_bin.test
jsk_2016_01_baxter_apc/test_data/.gitignore

From @wkentaro 's suggestion on #1362 
#1362 depends on this to test.

[jsk_2016_01_baxter_apc] Test motion for move-arm-to-bin with rosbag

---

jsk_apc2016_common/python/jsk_apc2016_common/segmentation_in_bin/bin_data.py

This class calculates location of corner points which are used to generate a mask image of a bin.
I have decided not to add corner points in Bin.msg's attributes because depending on how you choose to generate the mask image you may not need them.
In other words, BinPython contains codes that depend on algorithms.
Merge after #1368.

[Depends on #1368][jsk_apc2016_common] 	add BinData class that adds extra data to BinInfo msg

---

jsk_2016_01_baxter_apc/node_scripts/rbo_segmentation_in_bin_node.py

I have not decided how to update '/target_bin_name' which is a rosparam of a character in 'abcdefghijkl'.
--> WIP

[jsk_2016_01_baxter_apc] Add node version of RBOSegmentationInBin

---

jsk_2016_01_baxter_apc/CMakeLists.txt
jsk_2016_01_baxter_apc/package.xml
jsk_2016_01_baxter_apc/scripts/download_test_data.sh
jsk_2016_01_baxter_apc/test/test-move-arm-to-bin.l
jsk_2016_01_baxter_apc/test/test_move_arm_to_bin.test
jsk_2016_01_baxter_apc/test_data/.gitignore

[jsk_2016_01_baxter_apc] Add rosbag test

---

jsk_2016_01_baxter_apc/node_scripts/rbo_segmentation_in_bin_node.py
jsk_apc2016_common/python/jsk_apc2016_common/segmentation_in_bin/segmentation_in_bin_helper.py

For debugging and logging
print -> rospy.loginfo
error IO -> rospy.logerr

[jsk_2016_01_baxter_apc] use rospy debug tools

---

jsk_2016_01_baxter_apc/launch/segmentation_in_bin.launch

launch file mentioned in #1396

[jsk_apc2016_common] add launch file that initiates segmentation_in_bin

---

jsk_2016_01_baxter_apc/node_scripts/rbo_segmentation_in_bin_node.py
jsk_apc2016_common/CMakeLists.txt
jsk_apc2016_common/msg/SegmentationInBinSync.msg
jsk_apc2016_common/package.xml
jsk_apc2016_common/src/rbo_topic_synchronizer.cpp

changed pull requested branch to master.
#1402

[jsk_apc2016_common] add cpp message synchronizer

---

jsk_2016_01_baxter_apc/launch/setup_softkinetic.launch

[jsk_2016_01_baxter_apc] softkinetic config modified

---

jsk_apc2016_common/scripts/setup_rbo_segmenter.bash

corresponding to submodule dir
https://github.com/yuyu2172/rbo-apc-object-segmentation/pull/1

[jsk_apc2016_common] add segmenter setup bash script

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
jsk_2016_01_baxter_apc/euslisp/main.l

check if target bin is exist.
if not skip the target bin.

[jsk_2016_01_baxter_apc] add :check-bin-exist method

---

jsk_2016_01_baxter_apc/launch/include/segmentation_for_each_hand.launch
jsk_2016_01_baxter_apc/launch/segmentation_in_bin.launch

[DependsOn #1417] [jsk_2016_01_baxter_apc] modify sib launch to use softkinetic camera

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
jsk_2016_01_baxter_apc/euslisp/main.l

[DependsOn #1417] [jsk_2016_01_baxter_apc] add :recognize-objects-segmentation-in-bin method

---

doc/jsk_2016_01_baxter_apc/milestone/0.3_stable_achievement_30points.rst
doc/jsk_2016_01_baxter_apc/milestone/0.4_new_gripper_stable_grasping.rst

Refine milestone document files

---

jsk_2016_01_baxter_apc/node_scripts/tf_bbox_to_mask.py

rbo_segmentation_node.py have three functions, mask image generation, spatial image generation and segmentation.
our idea is that it is easier to improve and debug if we split the rbo_segmentation_node.py into three node.

[jsk_2016_01_baxter_apc] modify func get_mask_img() into one node

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l

Fixes #1429 
Details are on comments in #1429

[Depends on #1432] [jsk_2016_01_baxter_apc] Tell heavy object from wall when using right arm

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l

[Depends on #1445] [jsk_2016_01_baxter_apc] Raise object height threshold of bending gripper

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l

Fixes #1447 
Details are on #1447

[jsk_2016_01_baxter_apc] Approach objects straight down

---

jsk_apc2016_common/data/object_data_2016.yaml
jsk_apc2016_common/python/jsk_apc2016_common/__init__.py
jsk_apc2016_common/python/jsk_apc2016_common/tests/__init__.py

[jsk_apc2016_common] apc2016 object name fixed and add test 

---

jsk_apc2016_common/CMakeLists.txt
jsk_apc2016_common/include/sib/cloud_to_spatial_features.h
jsk_apc2016_common/package.xml
jsk_apc2016_common/src/cloud_to_spatial_features.cpp

[jsk_apc2016_common] Spatial Preprocessing Node

---

jsk_2016_01_baxter_apc/test/test-ik-in-bin.l
jsk_2016_01_baxter_apc/test/test-move-arm-to-bin.l

[jsk_2016_01_baxter_apc] Suppress errors by IK in test

---

jsk_2016_01_baxter_apc/config/self_filter.yaml
jsk_2016_01_baxter_apc/launch/include/self_filter.launch
jsk_2016_01_baxter_apc/launch/recognition_in_hand.launch

[jsk_2016_01_baxter_apc] add robot self filter for apc2016 robot model

---

doc/jsk_apc2016_common/index.rst
doc/jsk_apc2016_common/rbo_segmenter.rst

[jsk_2016_01_baxter_apc] add doc for setup RBO segmenter

---

jsk_2016_01_baxter_apc/launch/include/segmentation_for_each_hand.launch
jsk_2016_01_baxter_apc/launch/include/sib_visualization.launch
jsk_2016_01_baxter_apc/launch/segmentation_in_bin.launch
jsk_2016_01_baxter_apc/rvizconfig/sib_may_fes.rviz
jsk_apc2016_common/include/sib/cloud_to_spatial_features.h
jsk_apc2016_common/msg/SegmentationInBinSync.msg
jsk_apc2016_common/node_scripts/rbo_segmentation_in_bin_node.py
jsk_apc2016_common/node_scripts/tf_bbox_to_mask.py
jsk_apc2016_common/src/cloud_to_spatial_features.cpp
jsk_apc2016_common/src/sib_topic_synchronizer.cpp

#1457 
1. #1465, #1466, #1467, #1468 
2. rviz config
3. changed launch file to visualize 
4. ~~bug fix for self filters written by @knorth55~~

[jsk_apc2016_common][jsk_2016_01_baxter_apc] Segmentation in bin may fes

---

jsk_2016_01_baxter_apc/config/self_filter.yaml
jsk_2016_01_baxter_apc/robots/right_vacuum_gripper.xacro

cherry-picked commits from gripper-v2 branch

[jsk_2016_01_baxter_apc] Right hand self filter fixed

---

jsk_apc2016_common/node_scripts/publish_bin_tf.py

Reverts start-jsk/jsk_apc#1493

Revert "[jsk_apc2016_common] publish_bin_tf now uses tf2_ros static_tf_publisher"

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l

[jsk_2016_01_baxter_apc] Fix move-arm-body->order-bin to be slow

---

jsk_2016_01_baxter_apc/launch/include/segmentation_for_each_hand.launch
jsk_apc2016_common/node_scripts/rbo_segmentation_in_bin_node.py

[jsk_2016_01_baxter_apc] compress rbo mask image to point cloud size

---

jsk_2016_01_baxter_apc/config/self_filter.yaml

[jsk_2016_01_baxter_apc] Increase padding of right gripper in self_filter

---

jsk_apc2016_common/python/jsk_apc2016_common/__init__.py

[jsk_apc2016_common] update comment out in get_object_data

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
jsk_2016_01_baxter_apc/euslisp/main.l

i will check if it works after buying USB3.0  extension cables.

[jsk_2016_01_baxter_apc] use segmentation_in_bin for both arm in main.l

---

jsk_2016_01_baxter_apc/config/self_filter.yaml

[jsk_2016_01_baxter_apc] modify left hand self filter

---

doc/jsk_2016_01_baxter_apc/logs/2016-05-21.rst

milestone 0.3.0 finished #1509

[jsk_2016_01_baxter] add 20160521 log

---

jsk_2016_01_baxter_apc/CMakeLists.txt
jsk_apc2016_common/CMakeLists.txt

Incorrect Indents
White space at the end of line
Needless white space
use cmakelint for checking https://github.com/richq/cmake-lint

[jsk_2016_01_baxter_apc | jsk_apc2016_common] CMakeLists syntax fixed

---

jsk_apc2016_common/CMakeLists.txt

[jsk_apc2016_common] Add cmake dependency on jsk_apc2016_common

---

jsk_apc2016_common/data/object_data_2016.yaml
jsk_apc2016_common/python/jsk_apc2016_common/tests/__init__.py

Closes #1354 
@pazeshun #1548 fix and add test 
- cherry-picked from #1548
- https://github.com/start-jsk/jsk_apc/pull/1548/commits/881b55f28b7dbe0222e78f14ee929fd44b24d921 split into two commits
- add graspability test checking range in [1,4]

[jsk_apc_2016_common][fixed and improved from #1548] Add graspability of new gripper

---

jsk_2016_01_baxter_apc/launch/main.launch
jsk_2016_01_baxter_apc/node_scripts/work_order.py
jsk_2016_01_baxter_apc/test/work_order.test

[jsk_2016_01_baxter_apc] work_order modified to apply for apc2016 objects

---

jsk_2016_01_baxter_apc/launch/main.launch
jsk_2016_01_baxter_apc/launch/segmentation_in_bin.launch

Closes https://github.com/start-jsk/jsk_apc/issues/1544

[jsk_2016_01_baxter_apc] Move publish_bin_info from sib to main.launch

---

jsk_2016_01_baxter_apc/launch/include/segmentation_for_each_hand.launch
jsk_2016_01_baxter_apc/launch/main.launch
jsk_2016_01_baxter_apc/launch/segmentation_in_bin.launch
jsk_2016_01_baxter_apc/launch/setup_softkinetic.launch

this is necessary to fix bond errors.

[jsk_2016_01_baxter_apc] Use standalone_complexed_nodelet for setup_softkinetic.launch

---

jsk_apc2016_common/node_scripts/rbo_segmentation_in_bin_node.py

#1519 
@knorth55, @pazeshun 
We need to change `main.l` to handle cases when rbo_sib fails.

[jsk_apc2016_common] rbo_segmentation_in_bin_node returns nothing when it fails to predict anything

---

jsk_2016_01_baxter_apc/test/work_order.test

[jsk_2016_01_baxter_apc] add apc2015 work_order test

---

jsk_2015_05_baxter_apc/launch/include/kinect2_torso.launch
jsk_2015_05_baxter_apc/launch/include/segmentation_each_object_in_bin.launch
jsk_2015_05_baxter_apc/launch/recognition_in_hand.launch
jsk_2015_05_baxter_apc/launch/segmentation_in_bin_gtol.launch
jsk_2015_05_baxter_apc/launch/setup_torso.launch
jsk_2016_01_baxter_apc/launch/recognition_in_hand.launch
jsk_2016_01_baxter_apc/launch/setup_torso.launch

[jsk_2015_05_baxter_apc | jsk_2016_01_baxter_apc] kinect2_torso launch use standalone complex nodelet

---

jsk_2015_05_baxter_apc/launch/include/kinect2_head.launch
jsk_2015_05_baxter_apc/launch/segmentation_in_bin_atof.launch
jsk_2015_05_baxter_apc/launch/setup_head.launch

[jsk_2015_05_baxter_apc] kinect2_head launch use standalone complex nodelet

---

jsk_2016_01_baxter_apc/euslisp/examples/picking-with-sib.l

To test only picking with SIB like `picking-with-clustering.l`

Add picking-with-sib.l

---

jsk_2016_01_baxter_apc/rvizconfig/sib_demo.rviz

add sib demo rviz

---

doc/tips_faq.rst

Add FAQ for problem related to machine tag

---

.mention-bot

Introduce facebook/mention-bot

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
jsk_2016_01_baxter_apc/euslisp/main.l

:try-to-pick-object use bbox for grasping

---

jsk_2016_01_baxter_apc/launch/segmentation_in_bin.launch

fix #1576 
you need https://github.com/knorth55/softkinetic/commit/55061fca79d69b46fe33556938ddc9a80cadbe7b

use depth_registered for softkinetic_camera

---

jsk_2016_01_baxter_apc/launch/include/segmentation_for_each_hand.launch

add image jsk image_resizer

---

jsk_2016_01_baxter_apc/scripts/download_test_data.py
jsk_2016_01_baxter_apc/test/sib_softkinetic.test

Test using the right softkinetic camera's topics.

Test using the right softkinetic camera's topics

---

jsk_2016_01_baxter_apc/launch/include/segmentation_for_each_hand.launch
jsk_2016_01_baxter_apc/launch/include/sib_visualization.launch
jsk_apc2016_common/node_scripts/rbo_segmentation_in_bin_node.py

Visualize target object posterior image as an overlaid image

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l

add timeout in method :recognize-objects-segmentation-in-bin

---

jsk_apc2016_common/node_scripts/publish_bin_info.py

publish_bin_info publishes bin-info thta is specified by the current json rosparam

publish_bin_info updates when json is updated

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l

modify gripper-angle to 90 in overlook pose

---

jsk_apc2016_common/node_scripts/publish_bin_info.py

merge after #1604 
related #1606

publish_bin_info additionally publishes bin's bounding box array

---

jsk_2016_01_baxter_apc/test/sib_softkinetic.test

error said that there was no robot description.

prevent sib_right_hand_test from producing error

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l

according to https://github.com/start-jsk/jsk_apc/pull/1647#discussion_r66212828

use local variable in :recognize-objects-segmentation-in-bin

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
jsk_2016_01_baxter_apc/euslisp/main-stow.l
jsk_2016_01_baxter_apc/launch/main_stow.launch

new PR to stow-task branch
Closes #1138

add stow task main program and launch file

---

jsk_2016_01_baxter_apc/launch/include/segmentation_each_object_in_tote.launch
jsk_2016_01_baxter_apc/launch/segmentation_in_tote.launch
jsk_2016_01_baxter_apc/launch/setup_softkinetic.launch

add euclid clustering in tote for stow task

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
jsk_2016_01_baxter_apc/euslisp/main-stow.l
jsk_2016_01_baxter_apc/launch/recognition_in_hand_for_stow.launch
jsk_2016_01_baxter_apc/launch/setup_torso.launch

add inside tote recognition launch and connect to main program

---

doc/jsk_2016_01_baxter_apc/apc2016_pick_trial.rst
doc/jsk_2016_01_baxter_apc/apc2016_stow_trial.rst
doc/jsk_2016_01_baxter_apc/index.rst

[doc] add apc2016 pick and stow trial doc

---

jsk_2016_01_baxter_apc/launch/recognition_in_hand_for_stow.launch
jsk_2016_01_baxter_apc/launch/setup_torso.launch

add vgg16 node for stow task

---

jsk_2016_01_baxter_apc/launch/include/vacuum_gripper.launch
jsk_2016_01_baxter_apc/src/enable_gripper.cpp
jsk_2016_01_baxter_apc/src/gripper_joint_states_publisher.cpp
jsk_2016_01_baxter_apc/src/gripper_trajectory_server.cpp

~~Works with #1654~~
Works with #1667

Make left gripper interface

---

jsk_2016_01_baxter_apc/firmware/gripper_front_manager_left.ino

Added firmware for arduino of new left gripper-v3.

Firmware for left gripper-v3 arduino

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
jsk_2016_01_baxter_apc/euslisp/main.l

Avoid collision to bin top in return_object and try-to-pick-object

---

jsk_apc2016_common/node_scripts/tf_bbox_to_mask.py

- 8uc1 cannot be seen with image_view
- jsk_perception/apply_mask does not work with 8uc1

Fix encoding of in bin mask: 8UC1 -> mono8

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
jsk_2016_01_baxter_apc/euslisp/main-stow.l
jsk_2016_01_baxter_apc/launch/recognition_in_hand_for_stow.launch

recognize object length in hand

---

.travis.rosinstall
.travis.yml

Close https://github.com/start-jsk/jsk_apc/issues/1619

Build on travis while travis testing

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
jsk_apc2016_common/node_scripts/publish_bin_info.py

with this PR, we do not need to use kinect_head

use bin_info_publish node for :recognize-bin-boxes

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
jsk_2016_01_baxter_apc/launch/include/segmentation_each_object_in_tote.launch

add SupervoxelSegmentation for picking from tote

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
jsk_2016_01_baxter_apc/euslisp/main-stow.l

add scale key in move-arm-body->bin

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
jsk_2016_01_baxter_apc/robots/baxter.yaml
jsk_2016_01_baxter_apc/robots/left_vacuum_gripper.xacro
jsk_2016_01_baxter_apc/robots/right_vacuum_gripper.xacro

Change vacuum pad to short one(SPB2f)

---

jsk_2015_05_baxter_apc/launch/include/kinect2_torso.launch
jsk_2015_05_baxter_apc/rvizconfig/adjust_kinect2_torso.rviz

Fix https://github.com/start-jsk/jsk_apc/issues/1684

Adjust kinect2_torso tf and add rvizconfig for that

---

jsk_2016_01_baxter_apc/euslisp/main-stow.l

i will test it on real robot.
Closes #1689

use avoid-shelf-pose instead of move-arm-body->bin to avoid quick move

---

jsk_2016_01_baxter_apc/firmware/gripper_front_manager_left.ino
jsk_2016_01_baxter_apc/firmware/gripper_front_manager_right.ino

新しい吸盤に合わせた圧力のしきい値に変更。900->840
ただしスポンジボールはある程度吸盤を押し付けないと把持判定が出ない。

changed threshold of pressure

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l

Detect grasps with pressure threshold 840 [hPa]

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
jsk_2016_01_baxter_apc/launch/main_stow.launch
jsk_apc2016_common/node_scripts/publish_bin_bbox.py
jsk_apc2016_common/node_scripts/publish_bin_info.py

cherry-pick of #1680 and add new node for for stow task

publish bin bbox for stow task

---

fc.rosinstall
jsk_2016_01_baxter_apc/launch/check_astra.launch
jsk_2016_01_baxter_apc/launch/include/astra_hand.launch
jsk_2016_01_baxter_apc/robots/baxter.xacro
jsk_2016_01_baxter_apc/rvizconfig/check_astra.rviz

- add astra camera launch
- remove unused softkinetic xacro
- add astra check launch because we cannot identify astra camera by id

add astra camera and its check launch

---

jsk_apc2016_common/scripts/labelme_multiple.py

1. After finish labeling, it automatically opens labelme with the next data in stack
2. save labeled masks as binary images
3. display id of the objects that need to be labeled
4. move labeled data to 'labeled' directory

labelme specialized for APC

---

fc.rosinstall
jsk_2016_01_baxter_apc/launch/include/astra_hand.launch

- **left hand**: https://drive.google.com/uc?id=0B9P1L--7Wd2vOUc1MVZkQktKZTA
- **right hand**: https://drive.google.com/uc?id=0B9P1L--7Wd2vamJEZ3RxV0pkcE0

Adjust depth_frame of left hand camera (calibrated on 2016-06-16-21-35-00)

---

jsk_2016_01_baxter_apc/src/gripper_joint_states_publisher.cpp

This fixes the problem described in jsk-ros-pkg/jsk_pr2eus#229 completely.
Cc. @k-okada

Push gripper joint states back of other joint states

---

jsk_2016_01_baxter_apc/launch/recognition_in_hand.launch

Because of not really calibrated kinect2 extrinsic parameters.

Stop doing self_filter while recognizing object in hand

---

jsk_apc2016_common/python/jsk_apc2016_common/__init__.py
jsk_apc2016_common/python/jsk_apc2016_common/tests/data/stow_layout_1.json

For https://github.com/start-jsk/jsk_apc/pull/1715

Visualize official stow json with APC2016 objects

---

jsk_2016_01_baxter_apc/euslisp/reset-pose.l

```bash
rosrun jsk_2016_01_baxter_apc reset-pose.l right
```

Add reset-pose script

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
jsk_2016_01_baxter_apc/euslisp/main-stow.l

add wait-opposite-arm when returning from bin

---

jsk_apc2016_common/node_scripts/publish_target_bin_info.py

mistake found in #1738.
sorry...

add forgotten import publish_target_bin_info

---

jsk_2016_01_baxter_apc/node_scripts/control_vacuum_gripper.py

```
rosrun jsk_2016_01_baxter_apc control_vacuum_gripper.py start left
rosrun jsk_2016_01_baxter_apc control_vacuum_gripper.py stop
rosrun jsk_2016_01_baxter_apc control_vacuum_gripper.py stop right
```

Control vacuum gripper with a script

---

jsk_2016_01_baxter_apc/euslisp/in-hand-data-collection-main.l
jsk_2016_01_baxter_apc/launch/in_hand_data_collection.launch

Write grasp success/fail log while data collection on table

---

jsk_2016_01_baxter_apc/launch/sib_kinect.launch

When running sib with kinect, run `sib_kinect.lauch` instead of `setup_softkinetic.launch`.

run sib with kinect

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
jsk_2016_01_baxter_apc/euslisp/main-stow.l

set boundary to  avoid arm from moving tote 

---

jsk_2016_01_baxter_apc/euslisp/examples/picking-with-sib.l

Enable to use kinect in picking-with-sib.l

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l

@pazeshun 
this PR prevents arms collision you saw yesterday
https://drive.google.com/file/d/0B5DV6gwLHtyJRzY4MzZVNEdmTFk/view?usp=sharing

modify view hand pose for stow-task

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l

Don't rotate objects in Bin

---

jsk_2015_05_baxter_apc/config/kiva_pod_interactive_marker.yaml
jsk_2016_01_baxter_apc/launch/include/astra_hand.launch

I fixed 1st element of rotation parameters (R of RPY??) so that pointclouds of bin is parallel to the ground.
I adjusted kiva_pod_base so that a mask for SIB looks good.
https://drive.google.com/file/d/0BzBTxmVQJTrGZGdOSzBDWkVqbFk/view?usp=sharing

astra cameras produce pointclouds of shelf edges that are parallel to the ground

---

jsk_apc2016_common/data/.gitignore
jsk_apc2016_common/scripts/train_segmenter_2016.py

#1423 
```
python train_segmenter_2016.py
```
You need to update rbo_segmentation submodule to use this.

train script for 2016 RBO dataset

---

jsk_2016_01_baxter_apc/launch/include/astra_hand.launch

Movies
https://drive.google.com/open?id=0B9P1L--7Wd2vTm1RbG9vdEl1a0E

Adjust depth frame of astra cameras on 2016-06-22 00:17:11

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l

fix bug in :cube->movable-region

---

jsk_2016_01_baxter_apc/firmware/vacuum_manager.ino
jsk_2016_01_baxter_apc/launch/include/vacuum_gripper.launch

Firmware for new circuit to control 220V vacuum cleaners.
I have to check this firmware and circuit with the new vacuum cleaners.
@pazeshun please review this.

Changes to use new vacuum cleaners

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l

新しい掃除機に変更したのでそれに合わせて圧力しきい値を更新。
ただし、掃除機の吸引力調整目盛りで容易に変わりうるし、左右の掃除機でも特性差がある気がする。

Changed pressure threshold 840 -> 810

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l

`:wait-interpolation-smooth` needs `send *ri* :angle-vector` before itself.

Fix position of wait-interpolation-smooth

---

jsk_2016_01_baxter_apc/euslisp/examples/picking-with-sib.l
jsk_2016_01_baxter_apc/euslisp/main.l

Prepare for logging

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
jsk_2016_01_baxter_apc/euslisp/main.l

rarmとlarmを愚直にcondで分ける頭の悪さ
動作未確認

Auto calib pressure threshold

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l

Separate norm calculation from `:ik->bin-entrance`

Make :ik->nearest-pose method

---

jsk_2016_01_baxter_apc/firmware/vacuum_manager.ino

This PR enables to turn off vacuum cleaners with toggle switch.
I tested this with real machine.

Fixed firmware to use toggle switch

---

jsk_2016_01_baxter_apc/euslisp/in-bin-data-collection-main.l
jsk_2016_01_baxter_apc/launch/in_bin_data_collection.launch
jsk_apc2016_common/node_scripts/tf_bbox_to_mask.py

Data is collected here: https://drive.google.com/open?id=0B9P1L--7Wd2vQ0NfVmNTS1pnemM

Data collection program for segmentation in bin

---

jsk_2016_01_baxter_apc/launch/include/segmentation_for_each_hand.launch

Align bounding boxes to robot base frame

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l

Perhaps this will temporarily solve #1757

Rolling gripper on closer point to robot

---

jsk_2016_01_baxter_apc/euslisp/main.l

trust pressure sensor when pick-object

Changed do-stop-grasp t

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
jsk_2016_01_baxter_apc/launch/main_stow.launch
jsk_2016_01_baxter_apc/node_scripts/stow_work_order_server.py
jsk_apc2016_common/data/object_data_2016.yaml

- consider total objects volume in bin
- consider bin points
- consider object in hand volume

add stow_work_order_server node

---

jsk_apc2016_common/node_scripts/fcn_segmentation_in_bin_node.py

Fix fcn sib bug that failed to publish anything even when the input is easy

---

jsk_2016_01_baxter_apc/launch/segmentation_in_bin.launch
jsk_2016_01_baxter_apc/launch/setup_astra.launch
jsk_2016_01_baxter_apc/launch/sib_kinect.launch

Currently, self filter stopped working. Without this PR, segmentation_in_bin.launch does not start.

stop using self filters

---

jsk_apc2016_common/CMakeLists.txt

- Eigen -> Eigen3
- Configuration in find_package
- Install programs
To fix http://build.ros.org/job/Ibin_uT64__jsk_apc2016_common__ubuntu_trusty_amd64__binary/13/console

Fix CMakeLists.txt to release on apt

---

doc/jsk_2016_01_baxter_apc/apc2016_pick_trial.rst

update apc 2016 pick doc

---

jsk_apc2016_common/data/.gitignore
jsk_apc2016_common/scripts/install_dataset.py
jsk_apc2016_common/scripts/install_dataset.sh

I added 30 data and combined them with previous data.
https://drive.google.com/drive/u/0/folders/0BzBTxmVQJTrGOUFPbkJWUGV3a3c

Reflect new dataset on install_dataset script

---

jsk_2016_01_baxter_apc/src/gripper_trajectory_server.cpp
jsk_2016_01_baxter_apc/src/minjerk.h

fixes #1857 
- output feedback continuously
- use minjerk  https://github.com/fkanehiro/hrpsys-base/blob/master/rtc/SequencePlayer/interpolator.cpp
output of previous code is
and this PR will outputs
current   limitation 
- code is super ugry
- assuming the joint-angle of servo is 0 when we strart this program

minjerk and continuous feedback

---

jsk_2016_01_baxter_apc/firmware/gripper_front_manager_right/gripper_front_manager_right.ino

Adjust right gripper firmware to gripper-v4

---

jsk_2016_01_baxter_apc/CMakeLists.txt

- this will fix http://build.ros.org/view/Ibin_uT64/job/Ibin_uT64__jsk_2016_01_baxter_apc__ubuntu_trusty_amd64__binary/139/console

CMakeLists.txt: need to set current directory to ROS_PACKAGE_PATH

---

jsk_2016_01_baxter_apc/data/astra/left_hand_depth.yaml
jsk_2016_01_baxter_apc/data/astra/left_hand_rgb.yaml
jsk_2016_01_baxter_apc/data/astra/right_hand_depth.yaml
jsk_2016_01_baxter_apc/data/astra/right_hand_rgb.yaml
jsk_2016_01_baxter_apc/launch/include/astra_hand.launch

add astra intrinsic calibration file

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
jsk_2016_01_baxter_apc/euslisp/main-stow.l
jsk_2016_01_baxter_apc/launch/setup_for_stow.launch

```
$ rl jsk_2016_01_baxter_apc baxter.launch
$ rl jsk_2016_01_baxter_apc setup_for_stow.launch
$ rl jsk_2016_01_baxter_apc main_stow.launch json:=~~
```
For https://github.com/start-jsk/jsk_apc/issues/1865#issuecomment-237410624

use fcn segmentation for stow task

---

jsk_2016_01_baxter_apc/euslisp/main.l

Slower fold-pose-back initialization for apc task

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
jsk_2016_01_baxter_apc/euslisp/main-stow.l
jsk_2016_01_baxter_apc/euslisp/main.l
jsk_2016_01_baxter_apc/package.xml

I confirmed that this works with overall apc **pick** demo.

Fit to apply_context_to_label_proba which is merged to jsk_perception

---

jsk_2016_01_baxter_apc/test/test-again-approach-bin-l.l

- comment out irtviewer drawing function
- set debug-view nil

compress debug log in rostest

---

fc.rosinstall

related to #1919 and https://github.com/start-jsk/jsk_apc/pull/1919#issuecomment-255526899

add baxter_simulator in fc.rosinstall

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l

related to #1904 
add methods to cancel angle-vector when arm detect grasping

add :wait-interpolation-until-grasp method

---

jsk_2016_01_baxter_apc/launch/check_baxter_urdf.launch

Add urdf checking launch

---

jsk_2016_01_baxter_apc/launch/baxter.launch
jsk_2016_01_baxter_apc/launch/include/baxter_moveit.launch
jsk_2016_01_baxter_apc/launch/include/baxter_moveit_controller_manager.launch.xml
jsk_2016_01_baxter_apc/launch/include/move_group.launch
jsk_2016_01_baxter_apc/launch/include/planning_context.launch
jsk_2016_01_baxter_apc/launch/include/trajectory_execution.launch.xml
jsk_2016_01_baxter_apc/robots/moveit_config/baxter.srdf.xacro
jsk_2016_01_baxter_apc/robots/moveit_config/baxter_base.srdf.xacro
jsk_2016_01_baxter_apc/robots/moveit_config/baxter_controllers.yaml
jsk_2016_01_baxter_apc/robots/moveit_config/joint_limits.yaml
jsk_2016_01_baxter_apc/robots/moveit_config/vacuum_gripper.srdf.xacro

Not package version of #1939 
@k-okada how about this?

add jskbaxter2 moveit_config

---

fc.rosinstall

For https://github.com/start-jsk/jsk_apc/issues/1711#issuecomment-261983958

Upgrade baxter_interface to jsk_apc branch

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l
jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter.l
jsk_2016_01_baxter_apc/launch/bimanual_stow_data_collection.launch

Requires https://github.com/jsk-ros-pkg/jsk_common/pull/1482
related to #1903 
- add transform_publisher for data collection
- add data collection launch
- improve stow task motion in `baxter-interface.l` 
- add distance in `:move-arm-body->bin-with-support-arm`
- add `dy` key in `:view-opposite-hand-pose`
- remove `:wait-interpolation` from `:hold-opposite-hand-object`
- fix warning message in `movable-region`
- refine `:try-to-pick-object-in-order-bin` motion

bimanual stow data collection

---

jsk_2016_01_baxter_apc/CMakeLists.txt
jsk_2016_01_baxter_apc/package.xml
jsk_2016_01_baxter_apc/setup.py
jsk_2016_01_baxter_apc/src/jsk_baxter_dxl_controllers/calib_required_joint_controller.py
jsk_2016_01_baxter_apc/src/jsk_baxter_dxl_controllers/prismatic_joint_controller.py

For prismatic joint in gripper-v5

Add calib_required_joint_controller

---

jsk_2016_01_baxter_apc/config/right_gripper/dxl_controllers.yaml
jsk_2016_01_baxter_apc/launch/include/gripper_dxl_controller.launch

MERGE AFTER #1945 
This PR includes launch file to launch controllers on dynamixel_controllers layer for gripper-v5

Add launch for gripper-v5 controllers

---

jsk_2016_01_baxter_apc/CMakeLists.txt
jsk_2016_01_baxter_apc/config/right_gripper/joint_state_controller.yaml
jsk_2016_01_baxter_apc/config/right_gripper/joint_trajectory_controller.yaml
jsk_2016_01_baxter_apc/config/right_gripper/ros_control.yaml
jsk_2016_01_baxter_apc/launch/include/gripper_ros_control.launch
jsk_2016_01_baxter_apc/package.xml
jsk_2016_01_baxter_apc/src/gripper_ros_control.cpp

Add ros_control nodes

---

jsk_2016_01_baxter_apc/config/right_gripper/dxl_controllers.yaml
jsk_2016_01_baxter_apc/config/right_gripper/ros_control.yaml
jsk_2016_01_baxter_apc/robots/right_vacuum_gripper.xacro

Calibrate gripper motor range and reduction

---

jsk_2016_01_baxter_apc/robots/left_vacuum_gripper.xacro
jsk_2016_01_baxter_apc/robots/right_vacuum_gripper.xacro

set `gazebo` tag in vacuum gripper

add gazebo tag in vacuum_gripper.xacro

---

jsk_2016_01_baxter_apc/config/right_gripper/dxl_controllers.yaml
jsk_2016_01_baxter_apc/src/jsk_baxter_dxl_controllers/calib_required_joint_controller.py

Fix polling frequency in calibration

---

jsk_2016_01_baxter_apc/config/right_gripper/dxl_controllers.yaml
jsk_2016_01_baxter_apc/robots/right_vacuum_gripper.xacro
jsk_2016_01_baxter_apc/src/jsk_baxter_dxl_controllers/calib_required_joint_controller.py

Add calib_speed and increase joint speed

---

jsk_2016_01_baxter_apc/config/right_gripper/dxl_controllers.yaml

The cause of this is hardware.

Re-calibrate finger_tendon_winder

---

jsk_2016_01_baxter_apc/config/right_gripper/ros_control.yaml
jsk_2016_01_baxter_apc/src/gripper_ros_control.cpp

Add error limit to gripper_ros_control

---

jsk_2016_01_baxter_apc/config/right_gripper/ros_control.yaml
jsk_2016_01_baxter_apc/src/gripper_ros_control.cpp

This improves #1963 . #1963 is not enough.

Add load limit to gripper_ros_control

---

jsk_2016_01_baxter_apc/launch/include/move_group.launch
jsk_2016_01_baxter_apc/launch/include/ompl_planning.yaml
jsk_2016_01_baxter_apc/launch/include/ompl_planning_pipeline.launch

`longest_valid_segment_fraction`: 0.05 -> 0.01
this solves moveit path simplification error `Computed path is not valid Invalid states...`
https://groups.google.com/forum/#!topic/moveit-users/tMOL-GmwCGw

add ompl_planning and update param

---

jsk_2016_01_baxter_apc/config/right_gripper/dxl_controllers.yaml
jsk_2016_01_baxter_apc/config/right_gripper/ros_control.yaml
jsk_2016_01_baxter_apc/src/gripper_ros_control.cpp

To grasp object with certain force

Realize stable grasping

---

jsk_2016_01_baxter_apc/euslisp/examples/picking-with-gripper-v5.l
jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l

Add an example of picking with gripper-v5

---

jsk_2016_01_baxter_apc/robots/left_vacuum_gripper.xacro
jsk_2016_01_baxter_apc/robots/right_vacuum_gripper.xacro

Fix #1893 
Thanks to @mmurooka
This PR solves problem to load robot model in gazebo.

add inertia tag in both gripper.urdf.xacro

---

jsk_2016_01_baxter_apc/euslisp/examples/picking-with-gripper-v5.l

Add `drag-out-narrow-object` and `drag-out-pencil-case`

Improve and add new picking to picking-with-gripper-v5.l

---

jsk_2016_01_baxter_apc/launch/main.launch
jsk_2016_01_baxter_apc/node_scripts/work_order_server.py
jsk_apc2016_common/resource/object_data/2016.yaml

Please see commit messages about what I did

Work order for gripper-v5

---

jsk_2016_01_baxter_apc/euslisp/test/ik-check.l

- use gripper to solve ik
- set rotation-axis :z
- clean up codes

fix ik-check to work proper with gripper-v2

---

jsk_apc2016_common/launch/object_segmentation_3d.launch
jsk_apc2016_common/scripts/install_trained_data.py

- Trained with dataset v2 (JSK + MIT) > 5k
- 148000 iterations
- Dataset in shelf + tote.

FCN32s-V2: Update fcn32s trained model

---

jsk_2016_01_baxter_apc/launch/include/astra_hand.launch

This will solve problem of tf looking up with playing rosbag.
**last argument to static_tf_publisher is period not rate**

Fix tf rate of camera 10 -> 50

---

jsk_2016_01_baxter_apc/robots/moveit_config/baxter_base.srdf.xacro
jsk_2016_01_baxter_apc/robots/moveit_config/vacuum_gripper.srdf.xacro

disable collision between
- display - screen
- gripper - pedestal 
- gripper - head

Disable collision in MoveIt!

---

jsk_2016_01_baxter_apc/launch/baxter_pick_sim.launch
jsk_2016_01_baxter_apc/launch/baxter_sim.launch
jsk_2016_01_baxter_apc/launch/baxter_stow_sim.launch

load jskbaxter without kiva_pod

add baxter_sim launch

---

jsk_apc2016_common/scripts/list_objects.py

```
% rosrun jsk_apc2016_common list_objects.py 
0: background
1: barkely_hide_bones
2: cherokee_easy_tee_shirt
3: clorox_utility_brush
4: cloud_b_plush_bear
5: command_hooks
6: cool_shot_glue_sticks
7: crayola_24_ct
8: creativity_chenille_stems
9: dasani_water_bottle
10: dove_beauty_bar
11: dr_browns_bottle_brush
12: easter_turtle_sippy_cup
13: elmers_washable_no_run_school_glue
14: expo_dry_erase_board_eraser
15: fiskars_scissors_red
16: fitness_gear_3lb_dumbbell
17: folgers_classic_roast_coffee
18: hanes_tube_socks
19: i_am_a_bunny_book
20: jane_eyre_dvd
21: kleenex_paper_towels
22: kleenex_tissue_box
23: kyjen_squeakin_eggs_plush_puppies
24: laugh_out_loud_joke_book
25: oral_b_toothbrush_green
26: oral_b_toothbrush_red
27: peva_shower_curtain_liner
28: platinum_pets_dog_bowl
29: …
```

Add script to list object names

---

jsk_apc2016_common/CMakeLists.txt
jsk_apc2016_common/samples/data/.gitignore
jsk_apc2016_common/scripts/install_sample_data.py

For https://github.com/start-jsk/jsk_apc/issues/2007

Add apc recognition samples with Fetch

---

jsk_arc2017_baxter/launch/collect_data_in_bin.launch

For https://github.com/start-jsk/jsk_apc/issues/2028

Fix typo in collect_data_in_bin.launch

---

jsk_arc2017_common/scripts/view_jsk_v1.py

For https://github.com/start-jsk/jsk_apc/issues/2028

Script to view dataset before/after annotated

---

jsk_arc2017_common/scripts/view_jsk_v1.py

- Show size of All and Annotated
- Show label names
```
% ./view_jsk_v1.py
==> Size of dataset: All: 45, Annotated: 26.
==> Press q to quit, and any other keys to go next.
```

Neat visualization of dataset

---

jsk_arc2017_common/node_scripts/and_scale_rosserial.py
jsk_arc2017_common/package.xml

Close #2054
- new file:   and_scale_rosserial.py

Read weight data from AND scale

---

jsk_arc2017_baxter/euslisp/lib/arc-interface.l

fix typo in arc-interface

---

jsk_arc2017_baxter/euslisp/lib/arc-interface.l

add wait condition for wait_for_user_input

---

jsk_arc2017_common/node_scripts/work_order_publisher.py

- sort cardboard by box size and give ABC name
- fix typo

Sort cardboard by box size in work_order_publisher.py

---

jsk_2016_01_baxter_apc/launch/baxter.launch
jsk_2016_01_baxter_apc/launch/include/astra_hand.launch
jsk_2016_01_baxter_apc/launch/include/astra_hand_rgv5.launch
jsk_2016_01_baxter_apc/launch/setup_for_pick.launch
jsk_2016_01_baxter_apc/launch/setup_for_stow.launch

Close #1707
```
% rosrun openni2_camera list_devices 
[ INFO] [1494737840.549513001]: [${node}] [OpenNI2DeviceListener::onDeviceConnected] Device "2bc5/0402@1/5" found.
[ INFO] [1494737840.549685795]: [${node}] [OpenNI2DeviceListener::onDeviceConnected] Device "2bc5/0402@1/3" found.
Found 2 devices:
Device #0:
Uri: 2bc5/0402@1/3 (Vendor: Orbbec    , Name: Orbbec, Vendor ID: 2bc5, Product ID: 402)
Warning: USB events thread - failed to set priority. This might cause loss of data...
Serial number: 16042710236
Device #1:
Uri: 2bc5/0402@1/5 (Vendor: Orbbec    , Name: Orbbec, Vendor ID: 2bc5, Product ID: 402)
Warning: USB events thread - failed to set priority. This might cause loss of data...
Serial number: 16042710220
```

Find automatically astra device_id

---

jsk_arc2017_common/package.xml

Fix missing dependency on jsk_data

---

.gitattributes

https://github.com/github/linguist#overrides

Ignore archive/ in github launguage stats

---

jsk_arc2017_baxter/euslisp/pick-main.l

fix https://github.com/start-jsk/jsk_apc/issues/2074#issuecomment-300992304

update midpose to go back fold-pose-back

---

jsk_arc2017_baxter/euslisp/pick-main.l

minor changes
- remove and more rosparam
- add TODO

refine place_object motion

---

jsk_arc2017_baxter/euslisp/lib/arc-interface.l
jsk_arc2017_baxter/euslisp/pick-main.l

Update https://github.com/start-jsk/jsk_apc/pull/2105

Improve pick motion (Improve PR #2105)

---

jsk_arc2017_baxter/firmware/gripper_v6/sensor_manager_right/sensor_manager_right.ino

Add Arduino firmware for right gripper-v6

---

jsk_2016_01_baxter_apc/CMakeLists.txt

remove unused include_dirs

---

jsk_arc2017_baxter/CMakeLists.txt
jsk_arc2017_baxter/euslisp/lib/arc-interface.l
jsk_arc2017_baxter/test/test-state-server.l
jsk_arc2017_baxter/test/test_state_server.test

- add state_server test
- add lint test for node_scripts
- add `:get-state` method in `arc-interface`

add state_server test

---

jsk_arc2017_baxter/euslisp/lib/pick-interface.l

fix typo in pick-interface.l

---

jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter.l
jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxterrgv5.l

For https://github.com/euslisp/jskeus/issues/434#issuecomment-306983106

Don't set link-list as nil in IK when it is unspecified

---

jsk_arc2017_baxter/euslisp/lib/arc-interface.l
jsk_arc2017_baxter/euslisp/lib/baxter-interface.l

Related #2139 
- move `:fold-pose-back` in arc-interface
- add `&rest args` in `:fold-pose-back`

move :fold-pose-back method in arc-interface

---

.gitmodules
.travis.yml

Better version of https://github.com/start-jsk/jsk_apc/pull/2128

Improvements of rosdep key and catkin build package options in jsk_travis

---

jsk_arc2017_baxter/firmware/gripper_v6/sensor_manager_right/sensor_manager_right.ino
jsk_arc2017_baxter/msg/GripperSensorStates.msg
jsk_arc2017_baxter/node_scripts/republish_gripper_sensor_states.py

To make Arduino stable for old proximity sensors.
@708yamaguchi Please test this with fetch and old sensors

Lighten GripperSensorStates msg

---

jsk_arc2017_baxter/firmware/gripper_v6/sensor_manager_right/sensor_manager_right.ino
jsk_arc2017_baxter/firmware/gripper_v6/sensor_manager_right_sparkfun/sensor_manager_right_sparkfun.ino
jsk_arc2017_baxter/msg/GripperSensorStates.msg
jsk_arc2017_baxter/node_scripts/republish_gripper_sensor_states.py

Depends on #2146 
Current of LED is important
cc @708yamaguchi

Add Arduino sketch for sparkfun sensor

---

jsk_arc2017_baxter/euslisp/lib/pick-interface.l
jsk_arc2017_baxter/euslisp/lib/stow-interface.l

Use fold-pose-back in arc-interface

---

jsk_arc2017_baxter/euslisp/lib/arc-interface.l
jsk_arc2017_baxter/euslisp/lib/pick-interface.l
jsk_arc2017_baxter/euslisp/lib/stow-interface.l

Fix for #2138 
I also revert offsets for bin overlook pose

Fix small bugs added when adding stow

---

fc.rosinstall

Temporary solution
https://github.com/jsk-ros-pkg/jsk_roseus/issues/524#issuecomment-308374783

Use roseus_smach from source

---

README.md
jsk_2016_01_baxter_apc/launch/include/vacuum_gripper.launch
jsk_arc2017_baxter/scripts/create_udev_rules
jsk_arc2017_baxter/udev/80-dxhub.rules
jsk_arc2017_baxter/udev/90-rosserial.rules
jsk_arc2017_baxter/udev/unique-num

Using the knowledge in https://unix.stackexchange.com/questions/105144/udev-rule-for-assigning-known-symlinks-for-identical-usb-serial-devices

Distinguish Arduino from other ttyUSB devices

---

jsk_arc2017_baxter/node_scripts/state_server.py

with this PR, you can kill `state_server` process with `Ctrl-c`

state_server accept Ctrl-C keyboard interruption

---

fc.rosinstall

Fix missing pcl_conversions in fc.rosinstall for PCL 1.8

---

jsk_arc2017_baxter/euslisp/lib/arc-interface.l
jsk_arc2017_baxter/euslisp/lib/baxter-interface.l
jsk_arc2017_baxter/euslisp/lib/pick-interface.l
jsk_arc2017_baxter/euslisp/lib/stow-interface.l
jsk_arc2017_baxter/launch/setup/baxter.launch
jsk_arc2017_baxter/launch/setup/baxter_sim.launch
jsk_arc2017_baxter/launch/setup/include/baxter_moveit.launch
jsk_arc2017_baxter/launch/setup/include/baxter_moveit_controller_manager.launch.xml
jsk_arc2017_baxter/launch/setup/include/gripper_v6_ros_control.launch
jsk_arc2017_baxter/launch/setup/include/move_group.launch
jsk_arc2017_baxter/launch/setup/include/ompl_planning_pipeline.launch
jsk_arc2017_baxter/launch/setup/include/planning_context.launch
jsk_arc2017_baxter/launch/setup/include/trajectory_execution.launch.xml
jsk_arc2017_baxter/robots/moveit_config/baxter.srdf.xacro
jsk_arc2017_baxter/robots/moveit_config/baxter_base.srdf.xacro
jsk_arc2017_baxter/robots/moveit_config/baxter_controllers.yaml
jsk_arc2017_baxter/robots/moveit_config/joint_limits.yaml
jsk_arc2017_baxter/robots/moveit_config/left_vacuum_gripper.srdf.xacro
jsk_arc2017_baxter/robots/moveit_config/ompl_planning.yaml
jsk_arc2017_baxter/robots/moveit_config/right_vacuum_gripper.srdf.xacro
jsk_arc2017_baxter/robots/right_vacuum_gripper.xacro

Merge after #2155 
I haven't tested with real robot yet.

add moveit config for grippper-v6

---

jsk_arc2017_baxter/euslisp/lib/pick-interface.l
jsk_arc2017_baxter/euslisp/pick-main.l
jsk_arc2017_baxter/euslisp/stow-main.l

Merge after #2166 
I haven't tested on real robot yet.

Add moveit path constraints for place object

---

doc/jsk_arc2017_common/nodes/visualize_json.md
jsk_arc2017_baxter/launch/main/pick.launch
jsk_arc2017_baxter/launch/main/stow.launch
jsk_arc2017_baxter/launch/setup/baxter.launch
jsk_arc2017_common/doc
jsk_arc2017_common/node_scripts/json_saver.py
jsk_arc2017_common/node_scripts/visualize_json.py
jsk_arc2017_common/samples/sample_json_saver.launch
jsk_arc2017_common/samples/sample_visualize_json.launch

Close https://github.com/start-jsk/jsk_apc/issues/2185

Online item_location_file json visualization

---

jsk_arc2017_baxter/launch/setup/include/astra_hand.launch

thanks to @YutoUchimi and @pazeshun
@YutoUchimi can you review this?

introduce left stereo astra camera

---

jsk_arc2017_baxter/launch/setup/include/stereo_astra_hand.launch

fork of https://github.com/start-jsk/jsk_apc/pull/2168

Calibrated extrinsic parameters of right_hand_stereo by @YutoUchimi

---

README.md
jsk_arc2017_common/launch/object_estimation_by_scale.launch
jsk_arc2017_common/scripts/create_udev_rules
jsk_arc2017_common/udev/70-scale.rules
jsk_arc2017_common/udev/unique-num

My previous thought was https://github.com/start-jsk/jsk_apc/pull/2171#discussion_r123929783, but scales are connected to sheeta.
So we need this.
I'll test this tomorrow.

Distinguish scales from other ttyUSB devices

---

jsk_arc2017_baxter/launch/setup/include/astra_external.launch
jsk_arc2017_baxter/launch/setup/include/in_hand_recognition.launch
jsk_arc2017_common/launch/object_classification.launch

Related to #2187 
merge after #2207 
waiting for upstream https://github.com/jsk-ros-pkg/jsk_recognition/pull/2142 https://github.com/jsk-ros-pkg/jsk_recognition/pull/2143 and https://github.com/jsk-ros-pkg/jsk_recognition/pull/2144
- add `astra_external.launch`
- add `in_hand_recognition.launch`
```
roslaunch jsk_arc2017_baxter in_hand_recognition.launch
```

Add in hand recognition launch

---

jsk_arc2017_baxter/launch/setup/setup_for_pick.launch
jsk_arc2017_baxter/launch/setup/setup_for_stow.launch

Reverts start-jsk/jsk_apc#2221

Revert "Apply stereo camera to setup_for_pick/stow.launch"

---

jsk_apc2016_common/launch/object_segmentation_3d.launch
jsk_arc2017_baxter/euslisp/lib/arc-interface.l
jsk_arc2017_baxter/launch/setup/setup_for_stow.launch
jsk_arc2017_common/launch/object_segmentation_3d.launch

waiting for upstream
required https://github.com/jsk-ros-pkg/jsk_recognition/pull/2151
- return `nil` when largest box is not found
- add `ignore_labels` `[0, 41]` in label_to_cpi
- use arc2017 object_segmentation_3d in stow task

ignore __shelf__ label in stow task

---

jsk_arc2017_baxter/euslisp/lib/baxter-interface.l

https://github.com/start-jsk/jsk_apc/pull/2235#discussion_r126157616

Add sleep in :wait-interpolation-until loop

---

jsk_arc2017_baxter/launch/setup/baxter.launch

this is for debugging.
if debug is `true`, `MotionPlanRequest` is published as a message.

add moveit debug arg in baxter.launch

---

fc.rosinstall

we need master branch of jsk_pr2eus

add jsk_pr2eus in fc.rosintall

---

jsk_arc2017_common/python/jsk_arc2017_common/utils.py

@knorth55 requested me to do this, because it causes high cpu load.

Memoize result of visualize_json

---

jsk_arc2017_baxter/euslisp/check-pinch-graspability.l

https://github.com/start-jsk/jsk_apc/issues/2177#issuecomment-314475278
で使用したeusのテストコードです。

test program for pinch

---

jsk_arc2017_baxter/euslisp/lib/baxter-interface.l

This improves :wait-interpolation-until logging for debugging.
Also enabling to change threshold of finger flex.

Improve :wait-interpolation-until

---

jsk_arc2017_baxter/euslisp/lib/baxter-interface.l
jsk_arc2017_baxter/euslisp/lib/pick-interface.l
jsk_arc2017_baxter/euslisp/lib/stow-interface.l
jsk_arc2017_baxter/launch/main/pick.launch
jsk_arc2017_baxter/launch/main/stow.launch

clean up controller section.
normally, `arm-controller` should not contain `head-controller`.
I need to check with real robot.

exclude head-controller from [l/r]arm-controller and add [l/r]arm-head-controller

---

jsk_arc2017_baxter/launch/setup/include/stereo_astra_hand.launch

Close https://github.com/start-jsk/jsk_apc/issues/2204
We calibrated camera coordinates using interactive marker with @knorth55 .
This is fully supported by @YutoUchimi 's intrinsic camera parameter calibration, thanks. :bowing_man: 
**After**
**Before**

Make @pazeshun happy by hand-eye calibration

---

jsk_arc2017_baxter/euslisp/lib/baxter-interface.l

waiting for upstream https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/313 
add `controller-type` in `:cancel-angle-vector`

add controller-type in cancel-angle-vector

---

jsk_arc2017_baxter/config/collect_data_in_shelf/shelf_marker.yaml
jsk_arc2017_baxter/euslisp/collect-data-in-shelf-main.l
jsk_arc2017_baxter/launch/main/collect_data_in_shelf.launch
jsk_arc2017_baxter/launch/setup/include/setup_source_location.xml

```bash
roslaunch jsk_arc2017_baxter baxter.launch moveit:=false
roslaunch jsk_arc2017_baxter stereo_astra_hand.launch
roslaunch jsk_arc2017_baxter collect_data_in_shelf.launch
```

Fix collect_data_in_shelf program with latest launch files

---

jsk_arc2017_baxter/euslisp/pick-main.l
jsk_arc2017_baxter/euslisp/stow-main.l

Add initialization of left hand

---

jsk_arc2017_common/experiments/annotate_2d_dataset_20170714/README.md
jsk_arc2017_common/scripts/annotate_2d_dataset.py

Usage
-----
Please see this. @YutoUchimi @708yamaguchi
```bash
gdown 'https://drive.google.com/uc?id=0B9P1L--7Wd2vYzdfX3YtcTMwMm8'
unzip dataset_jsk_v3_20160614_yamaguchi.zip
rosrun jsk_arc2017_common annotate_2d_dataset.py -d dataset_jsk_v3_20160614_yamaguchi
gdown 'https://drive.google.com/uc?id=0B9P1L--7Wd2vMkNGWEV1LU9ZTDg'
unzip dataset_jsk_v3_20160614_uchimi.zip
rosrun jsk_arc2017_common annotate_2d_dataset.py -d dataset_jsk_v3_20160614_uchimi
```
How to annotate?
------------------
1. Annotate shelf (41).
2. Annotate objects, and **you must annotate all objects inside the shelf region** (1 - 40).
3. If you have region in-confident about class, you can annotate it as ignored region (-1).
4. If you have gripper region inside of shelf, you can annotate it as unknown object region (0). …

Do 2d annotation on dataset_v3_20160614

---

jsk_arc2017_baxter/launch/setup/include/scale.launch
jsk_arc2017_common/node_scripts/ekew_i_driver.py

Detect serial blocked and restart

---

.travis.yml
jsk_2016_01_baxter_apc/CMakeLists.txt
jsk_arc2017_common/node_scripts/ekew_i_driver.py

do not use travis-python

---

jsk_arc2017_common/scripts/view_jsk_v1.py

@YutoUchimi @708yamaguchi 
```
rosrun jsk_arc2017_common view_2d_dataset.py -d <dataset_dir>
```

Add script to visualize annotated 2d dataset

---

.gitmodules
.travis.rosinstall
.travis.yml
fc.rosinstall
jsk_arc2017_common/scripts/install_data.py

This will fix ci failures on 
- https://github.com/start-jsk/jsk_apc/pull/2292
- https://github.com/start-jsk/jsk_apc/pull/2286

Fix version of jsk_robot we depend on

---

jsk_arc2017_baxter/robots/moveit_config/joint_limits.yaml

this PR fixed moveit slow trajectory.
related to https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/310#issuecomment-315520045

add max_acceleration for right_s0 in joint_limits

---

jsk_arc2017_baxter/rvizconfig/pick.rviz
jsk_arc2017_baxter/rvizconfig/stow.rviz

Update to show left arm and visualize_json topic
- pick.rviz
- stow.rviz

update pick.rviz and stow.rviz

---

jsk_arc2017_common/experiments/annotate_2d_dataset_20170714/README.md

@YutoUchimi Please upload annotated data to https://github.com/start-jsk/jsk_apc/tree/master/jsk_arc2017_common/experiments/annotate_2d_dataset_20170714#memo by below commands:
```
mv dataset_jsk_v3_20160614_uchimi dataset_jsk_v3_20160614_uchimi_annotated
zip -r dataset_jsk_v3_20160614_uchimi_annotated.zip dataset_jsk_v3_20160614_uchimi_annotated
gshell cd --with-id 0B9P1L--7Wd2vYmVMeXFpbWdINE0
gshell upload dataset_jsk_v3_20160614_uchimi_annotated.zip
```

Update README.md for annotate_2d_dataset_20170714

---

jsk_arc2017_baxter/firmware/gripper_v6/sensor_manager_left_sparkfun/sensor_manager_left_sparkfun.ino
jsk_arc2017_baxter/firmware/gripper_v6/sensor_manager_right_sparkfun/sensor_manager_right_sparkfun.ino

Close #2306 
The value of flex sensor improves like below:
|Before this change|After this change|
|---|---|
|![screenshot from 2017-07-18 20 20 45](https://user-images.githubusercontent.com/14994939/28314721-a1dc0392-6bf6-11e7-810a-01bcd92292b6.png)|![screenshot from 2017-07-19 16 35 35](https://user-images.githubusercontent.com/14994939/28357203-96fcc81c-6ca5-11e7-93a7-0de9d5863beb.png)|
- Stop proximity sensor before measuring flex

Stabilize flex sensor

---

jsk_arc2017_baxter/euslisp/lib/pick-interface.l

i tested with real robot, too.

modify place object position for stable place

---

jsk_arc2017_common/node_scripts/weight_candidates_refiner.py

publish prev_weight_sum and you can compare with weight_sum msg

publish prev_weight_sum for debugging

---

jsk_arc2017_common/node_scripts/weight_candidates_refiner.py

Fix typo in weight_candidates_refiner.py

---

jsk_arc2017_common/node_scripts/ekew_i_driver.py

~/output_rawというtopicで体重計の読みを常にpublishするようにしました。
物をつかむとき、baxterの手が物品に当たるのを、体重計でも検知しようとおもっています。

always publish raw weight value

---

jsk_arc2017_common/node_scripts/visualize_json.py
jsk_arc2017_common/python/jsk_arc2017_common/utils.py

Mark ordered objects with red circle in VisualizeJSON

---

jsk_arc2017_baxter/euslisp/lib/arc-interface.l

pinchするとき、直動関節の長さを75にするようにしました。（今まではpinchするときに指が地面にあたっていた。）

change prismatic joint length during pinch

---

jsk_arc2017_baxter/euslisp/lib/arc-interface.l
jsk_arc2017_baxter/euslisp/lib/baxter-interface.l

depend on #2263 
pinchで腕をさげる時に、proximity による接触判定も追加しました。

Add finger proximity condition to try-to-pinch-object

---

jsk_arc2017_baxter/euslisp/lib/arc-interface.l

pinchの時、boundingboxの辺に腕を合わせようとしてbaxterの腕が余分に回転するのを解消しました。

solve ik easier in pinch

---

jsk_arc2017_common/config/object_graspability.yaml
jsk_arc2017_common/node_scripts/work_order_publisher.py
jsk_arc2017_common/python/jsk_arc2017_common/__init__.py
jsk_arc2017_common/python/jsk_arc2017_common/data.py
jsk_arc2017_common/scripts/list_graspability.py

- add func `get_object_graspability()`
- add `list_graspability.py` script
- sort work order by graspability

sort work order by graspability

---

jsk_arc2017_baxter/euslisp/lib/arc-interface.l
jsk_arc2017_baxter/euslisp/lib/pick-interface.l
jsk_arc2017_baxter/euslisp/lib/stow-interface.l

add object in hand as attatched object.
this PR avoid collision between object-in-hand and rack.

add object-in-hand as attached object scene

---

jsk_arc2017_baxter/robots/left_gripper_v6/dxl_controllers.yaml

by @pazeshun 
Same as https://github.com/start-jsk/jsk_apc/pull/2283#issue-242918173

Re-calibrate vacuum pad joint

---

jsk_arc2017_baxter/euslisp/lib/arc-interface.l

this PR is for approaching object using prismatic joint mainly

use prismatic-based approach in :pick-object

---

jsk_arc2017_baxter/launch/setup/setup_for_pick.launch

reset weight error for pick task

---

jsk_arc2017_baxter/euslisp/lib/arc-interface.l

Bin
---
- Left Arm, Bin A
- Left Arm, Bin B
- Right Arm, Bin B
- Right Arm, Bin C
Tote
----
- Left Arm
- Right Arm

Modify overlook-pose offset

---

jsk_arc2017_baxter/euslisp/lib/arc-interface.l

Reverts start-jsk/jsk_apc#2353

Revert "reset gripper rotation after lifting object"

---

jsk_arc2017_common/launch/object_segmentation_3d.launch
jsk_arc2017_common/scripts/install_data.py

**previous model**
```
Accuracy: 57.0526                
AccClass: 59.8644                
Mean IoU: 36.6730                
Fwav Acc: 44.7225   
```
**new model**
```
Accuracy: 90.8185
AccClass: 89.5070
Mean IoU: 79.3201
Fwav Acc: 83.3791
```

FCN32s trained using natural dataset (datasetV3)

---

jsk_arc2017_baxter/euslisp/lib/arc-interface.l

do not stop-grasp in pinch

---

jsk_arc2017_common/config/object_graspability.yaml

pinchのgraspabilityが2の物体はpinchせず、suctionのみでつかむようにしました。

pinch graspability 2 -> 3

---

jsk_arc2017_common/launch/object_segmentation_3d.launch
jsk_arc2017_common/scripts/install_data.py

```
% ./evaluate.py logs/fcn32s_CFG-009_DATASET-v3_OPTIMIZER-Adam_WEIGHT_DECAY-0.0005_LR-1e-05_MAX_ITERATION-150000_VCS-c0bff11_TIME-20170723-112528/models/fcn32s_dataset_v3_cfg009_20170724.npz
Accuracy: 93.7259
AccClass: 92.3574
Mean IoU: 84.6101
Fwav Acc: 88.3183
```

148000 iterations with Datasetv3

---

jsk_arc2017_baxter/euslisp/lib/arc-interface.l
jsk_arc2017_baxter/euslisp/lib/pick-interface.l
jsk_arc2017_baxter/euslisp/lib/stow-interface.l

In order to avoid hard place pose, we reset pose when robot lift object.

lift object set :rotation-axis t to avoid collision

---

.travis.yml

increase NUMBER_OF_LOGS_TO_KEEP to 10

---

jsk_arc2017_baxter/euslisp/lib/arc-interface.l

move arm lower when pick object

---

jsk_arc2017_baxter/euslisp/lib/pick-interface.l
jsk_arc2017_baxter/euslisp/lib/stow-interface.l

I haven't tested with real robot

return-from :pick-object faster when graspingp nil

---

jsk_arc2017_baxter/euslisp/pick-main.l
jsk_arc2017_baxter/euslisp/stow-main.l

I haven't tested with real robot.

set less recognize trial times

---

jsk_arc2017_baxter/euslisp/lib/pick-interface.l

I haven't tested with real robot.

refine place motion for cardboard :a and :b

---

jsk_arc2017_baxter/euslisp/lib/arc-interface.l

I haven't tested in real robot.

Speed up finger motion in suction

---

jsk_arc2017_baxter/euslisp/lib/arc-interface.l

Skip IK when IK fails in picking

---

jsk_arc2017_baxter/euslisp/lib/arc-interface.l

Moved from https://github.com/start-jsk/jsk_apc/pull/2403

Remove unix::sleep in arc-interface.l

---

jsk_arc2017_baxter/euslisp/lib/pick-interface.l
jsk_arc2017_baxter/euslisp/lib/stow-interface.l

I haven't tested on real robot yet.

Return from :verify-object if classified probability < proba-thre

---

jsk_arc2017_baxter/euslisp/lib/arc-interface.l

Change pinch motion near walls

---

jsk_arc2017_baxter/euslisp/lib/arc-interface.l

Just change offset to pinch well

Fix pinch motion for pick task

---

jsk_arc2017_baxter/launch/setup/include/stereo_astra_hand.launch
jsk_arc2017_baxter/launch/setup/setup_for_pick.launch
jsk_arc2017_baxter/launch/setup/setup_for_stow.launch

FIXME: we need different extrinsic params for pick and stow.

Update hand-eye extrinsic params

---

jsk_arc2017_baxter/euslisp/lib/stow-interface.l

stowでpinchしたあとにplaceする時、腕を下げる量を小さくしたのと、IKが解けなかった時に腕を降ろさずにbinに物品を落とすようにしました。

place object from higher place

---

jsk_arc2017_baxter/node_scripts/sanity_check_for_pick.py
jsk_arc2017_baxter/node_scripts/sanity_check_for_setup_for_pick.py

This must be called after baxter/setup_for_pick and pick.launch

Check sanity of system (topics/nodes) by script

---

jsk_arc2017_baxter/euslisp/lib/arc-interface.l

[Depends on #2480] Don't move arm in first suction

---

jsk_arc2017_baxter/euslisp/lib/arc-interface.l
jsk_arc2017_baxter/euslisp/lib/pick-interface.l

I compiled files and searched for unset local variables.

fix unset local variables

---

jsk_arc2017_common/data/json/sample_pick_task/item_location_file.json
jsk_arc2017_common/data/json/sample_pick_task/order_file.json
jsk_arc2017_common/node_scripts/json_saver.py
jsk_arc2017_common/node_scripts/work_order_publisher.py
jsk_arc2017_common/samples/sample_work_order_publisher.launch

1A5 is bigger than 1B2, but 1A5 is never used for cardboard_C and 1B2 for cardboard_B

fix bug in cardboard ids

---

jsk_arc2017_baxter/launch/setup/baxter.launch
jsk_arc2017_baxter/launch/setup/include/axis_camera.launch
jsk_arc2017_baxter/rvizconfig/pick.rviz
jsk_arc2017_baxter/samples/sample_axis_camera.launch

Use axis camera to record baxter motion

---

jsk_arc2017_baxter/euslisp/lib/pick-interface.l
jsk_arc2017_baxter/euslisp/lib/stow-interface.l

Open fingers when placing

---

fc.rosinstall

All commits in jsk_apc branch were merged to the master.

Use master branch of jsk_recognition

---

jsk_arc2017_baxter/launch/setup/baxter.launch
jsk_arc2017_baxter/scripts/force_recognize_usb_devices

Close https://github.com/start-jsk/jsk_apc/issues/2528
It diconnect and reconnect usbs by software.
```
rosrun jsk_arc2017_baxter force_recognize_usb_devices
```

Add script to forcely recognize usbs

---

.travis.yml
jsk_arc2017_baxter/euslisp/lib/arc-interface.l

Use end-coords-interpolation in picking

---

jsk_arc2017_baxter/CMakeLists.txt

Fix for not finding force_proximity_ros on build.ros.org

---

jsk_2015_05_baxter_apc/euslisp/lib/util.l

```
1.irteusgl$ (timestamp)
(2017 8 7 23 49 17)
2.irteusgl$ (timestamp-string)
"20170807_234924"
3.irteusgl$ (timestamp-string :control-string "~A~0,2d~0,2d")
"20170807"
```

add timestamp functions in util.l

---

jsk_2016_01_baxter_apc/launch/baxter.launch
jsk_2016_01_baxter_apc/launch/baxterrgv5.launch
jsk_2016_01_baxter_apc/launch/setup_for_pick.launch
jsk_2016_01_baxter_apc/launch/setup_for_stow.launch

move camera launch in setup launch

---

jsk_2015_05_baxter_apc/euslisp/lib/util.l

Reverts start-jsk/jsk_apc#2542
We can use https://github.com/start-jsk/jsk_apc/pull/2542#issuecomment-320816526

Revert "add timestamp functions in util.l"

---

fc.rosinstall
jsk_arc2017_baxter/euslisp/lib/baxter-interface.l
jsk_arc2017_baxter/euslisp/sanity-check-gripper-v6.l
jsk_arc2017_baxter/launch/setup/baxter.launch

Close https://github.com/start-jsk/jsk_apc/issues/2526
Depends on https://github.com/jsk-ros-pkg/jsk_robot/pull/817

Enable sanity check of action servers

---

jsk_arc2017_baxter/launch/setup/baxter.launch
jsk_arc2017_baxter/launch/setup/include/baxter.machine
jsk_arc2017_baxter/launch/setup/include/gripper_arduinos.launch
jsk_arc2017_baxter/launch/setup/include/gripper_v6_dxl_controller.launch
jsk_arc2017_baxter/launch/setup/include/scale.launch
jsk_arc2017_baxter/launch/setup/include/setup_gripper_v6.launch
jsk_arc2017_baxter/launch/setup/setup_for_pick.launch

Communication to hand cameras are unstable, and I couldn't make left-hand-right-camera works during the task.

Launch arduino/dxl/scales on baxter-c2

---

fc.rosinstall

Install rosserial from source to suppress warning

---

jsk_arc2017_common/experiments/create_item_data/.gitignore
jsk_arc2017_common/experiments/create_item_data/01_create_info_json.py
jsk_arc2017_common/experiments/create_item_data/02_organize_image_files.py
jsk_arc2017_common/experiments/create_item_data/03_annotate_image_files.py
jsk_arc2017_common/experiments/create_item_data/README.md
jsk_arc2017_common/experiments/create_item_data/view_item_data.py

```bash
mkdir -p item_data/Noodle_Seafood
mv ~/Downloads/Photos.zip item_data/Noodle_Seafood
(cd item_data/Noodle_Seafood && unzip Photos.zip && rm item_data/Photos.zip)
./01_create_info_json.py
./02_organize_image_files.py
./03_annotate_image_files.py
```
```bash
git clone https://github.com/wkentaro/mvtk.git
(cd mvtk && ./install.sh)
./view_item_data.py item_data
```

Create ItemData by taking photos

---

.travis.yml

On travis, it fails without no clue to fix.
Moved from #2579

Run test on Jenkins

---

docker/Dockerfile

This is needed to resolve dependencies correctly.

Add --rosdistro option to rosdep Dockerfile

---

jsk_2016_01_baxter_apc/euslisp/lib/baxter-interface.l

use avs-raw with :fast in pick-object

---

jsk_arc2017_common/data/models/.gitignore
jsk_arc2017_common/data/models/fcn32s.npz
jsk_arc2017_common/scripts/install_data.py

In order to avoid error in bloom.

Create fcn32s.npz symlink by install_data.py

---

jsk_arc2017_baxter/package.xml

Close https://github.com/start-jsk/jsk_apc/issues/2598

Install roslint + rostest for testing jsk_arc2017_baxter

---

.travis.yml

We'd like to avoid using jenkins as much as possible.

Use Travis instead of Jenkins

---

jsk_apc2016_common/launch/object_segmentation_3d.launch

Improve visualization (alpha: 0.7, tile_image)

---

jsk_arc2017_baxter/include/jsk_arc2017_baxter/tendon_transmission_loader.h

Fix https://github.com/start-jsk/jsk_apc/pull/2633#issuecomment-390508492

transmission_interface::TransmissionSharedPtr = TransmissionPtr

---

jsk_arc2017_baxter/euslisp/lib/pick-interface.l

This was introduced by the demo on April 2018.

Remove head_pan rotation while picking

---

fc.rosinstall

Close https://github.com/start-jsk/jsk_apc/issues/2642

Add jsk_pr2eus to fc.rosinstall

---

jsk_arc2017_baxter/euslisp/sanity-check-gripper-v6.l
jsk_arc2017_baxter/launch/setup/baxter.launch
jsk_arc2017_baxter/launch/setup/include/gripper_arduinos.launch
jsk_arc2017_baxter/launch/setup/include/setup_gripper_v6.launch

For https://groups.google.com/a/jsk.imi.i.u-tokyo.ac.jp/forum/#!topic/baxter/dj4RfMT24PI
**Usage**
```bash
roslaunch jsk_arc2017_baxter baxter.launch launch_left:=false respawn_arduino:=false
```

Add if-blocks to use only the single arm

---

docker/indigo/Dockerfile
docker/kinetic/Dockerfile

From https://github.com/start-jsk/jsk_apc/pull/2664#issuecomment-430179884

Add dist-upgrade to Dockerfiles

---

jsk_arc2017_baxter/euslisp/pick-main.l
jsk_arc2017_baxter/euslisp/stow-main.l

From https://github.com/start-jsk/jsk_apc/pull/2661#pullrequestreview-157527987
Merge this PR or #2661 
Tested in real robot

Fix :recognize-object state to return t or nil

---

jsk_arc2017_baxter/euslisp/lib/arc-interface.l

add `object-index` args to set picking object

add object-index key args in :pick-object-in-movable-region

---

jsk_arc2017_baxter/robots/baxter.xacro
jsk_arc2017_baxter/robots/left_vacuum_gripper.xacro
jsk_arc2017_baxter/robots/right_vacuum_gripper.xacro

add finger arg for xacro

---

fc.rosinstall

remove jsk_pr2eus in fc.rosinstall

---

jsk_arc2017_baxter/launch/setup/include/gripper_arduinos.launch
jsk_arc2017_baxter/node_scripts/check_arduino.py

- add check_arduino node
- if no topic is published but node is running, kill the node

Add check arduino node

---

README.md
upboard.rosinstall
upboard.rosinstall.kinetic

add upboard rosinstall for baxter system

add upboard rosinstall

---

jsk_arc2017_baxter/CMakeLists.txt
jsk_arc2017_baxter/package.xml

add `dynamixel_controllers` as `build_depend`

add dynamixel_controllers as build_depend

---

demos/instance_occlsegm/ros/synthetic2d/package.xml

add missing message_generation build_depend

add message_generation for build_depend in synthetic2d

---

demos/grasp_fusion/tests/data_tests/test_extractall.py
demos/instance_occlsegm/tests/data_tests/test_extractall.py

Close https://github.com/start-jsk/jsk_apc/pull/2702

Stop using VOCdevkit tar file to test extractall function

---

.travis.rosinstall
.travis.rosinstall.melodic
.travis.yml
demos/grasp_fusion/requirements.txt
demos/instance_occlsegm/requirements.txt
docker/Dockerfile
docker/hooks/build
jsk_apc2016_common/CMakeLists.txt

- update travis
- fix travis build
- add melodic test

Update and fix travis

---

jsk_arc2017_common/scripts/install_data.py

For https://github.com/start-jsk/jsk_apc/pull/2707#issuecomment-627229028

Stop downloading unused model checkpoints

---

docker/Dockerfile

I update dockerfile not to build all files in Indigo

update docker file for indigo

---

demos/grasp_fusion/ros/grasp_fusion/package.xml
demos/instance_occlsegm/ros/instance_occlsegm/package.xml

Closes #2718 
This PR is for https://github.com/start-jsk/jsk_apc/issues/2718#issuecomment-651669471

[grasp_fusion, instance_occlsegm] Explicitly installs python-tk for 'import matplotlib.pyplot'

---

demos/instance_occlsegm/README.md

Close https://github.com/start-jsk/jsk_apc/issues/2727

Fix typo in demos/instance_occlsegm/README.md

---

fc.rosinstall.melodic

add `fc.rosinstall.melodic` for melodic PC

add fc.rosinstall.melodic

---

demos/instance_occlsegm/examples/instance_occlsegm/instance_occlusion_segmentation/train.py
demos/instance_occlsegm/examples/instance_occlsegm/instance_segmentation/train_common.py
demos/instance_occlsegm/examples/instance_occlsegm/occlusion_segmentation/train.py
demos/instance_occlsegm/examples/instance_occlsegm/semantic_segmentation/train.py
demos/instance_occlsegm/examples/synthetic2d/instance_occlusion_segmentation/train.py

https://docs.chainer.org/en/stable/chainermn/reference/index.html#chainermn.create_communicator
`hierarchical` is no more available...

change to pure_nccl: hierarchical is no more available

---

.github/workflows/indigo.yaml
.github/workflows/kinetic.yml
.github/workflows/melodic.yml

add github actions for indigo, kinetic and melodic.
- exclude `instance_occlsegm` and `grasp_fusion` test because of gdrive download maximum trials

add github actions

---

.travis.rosinstall
.travis.rosinstall.melodic
demos/baxtergv6_apc2016/euslisp/lib/baxter-interface.l
demos/sphand_ros/sphand_driver/config/left_gripper_v7/dxl_controllers.yaml
demos/sphand_ros/sphand_driver/config/left_gripper_v8/dxl_controllers.yaml
demos/sphand_ros/sphand_driver/config/right_gripper_v7/dxl_controllers.yaml
demos/sphand_ros/sphand_driver/euslisp/lib/baxterlgv8-interface.l
jsk_arc2017_baxter/euslisp/lib/baxter-interface.l
jsk_arc2017_baxter/euslisp/lib/baxterlgv7-interface.l
jsk_arc2017_baxter/robots/left_gripper_v6/dxl_controllers.yaml
jsk_arc2017_baxter/robots/right_gripper_v6/dxl_controllers.yaml

Depends on https://github.com/pazeshun/dynamixel_motor/pull/7

Use calib_required_joint_controller in dynamixel_controllers

---

demos/grasp_fusion/ros/grasp_fusion/node_scripts/mask_rcnn_instance_segmentation.py
demos/grasp_prediction_arc2017/ros/grasp_prediction_arc2017/nodes/grasp_style_server_book_picking.py
demos/grasp_prediction_arc2017/ros/grasp_prediction_arc2017/nodes/work_order_publisher_book_picking.py
docker/Dockerfile

- Kinetic build on docker hub failed due to `test_catkin_virtualenv*`: https://hub.docker.com/repository/registry-1.docker.io/jskrobotics/jsk_apc/builds/0770591d-1e0b-4ff0-8d65-8ca96b939df2
- Noetic test on travis failed due to linter (`grasp_fusion` and `grasp_prediction_arc2017` are not check on github actions): https://app.travis-ci.com/github/start-jsk/jsk_apc/jobs/608676496

Fix docker & travis
